Return-To-The-Roots/s25client

- release/bin/macos/rttr.command
Some cleanups:
- removed unnecessary subshells
- error output should go to STDERR
- rewritten remaining latin1 character, it's now plain ASCII
- deleted trailing whitespace
This has a high chance of fixing issue #20, but I have no MacOSX machine
to test this on.
> Make rttr.command a plain sh(1) script for better portability.

- build/cmake.sh
- build/start.sh
- start.sh
While here, remove 8bit chars to make it UTF-8, remove some unneeded
subshells and allow all possible spellings of 'yes'.
> Make build/cmake.sh a plain sh(1) script for better portability.

- build/postinstall.sh.cmake
The binary to use is simply objcopy, set this and don't override or
append. Fix the test for checking whether objcopy works, the file
existence test is not sufficient as we need to search in $PATH.
> Fix objcopy on FreeBSD, we don't support cross-builds under FreeBSD.

- src/SerializedGameData.cpp
SerializedGameData: Use std::set's find for containment check
std::set::find is O(log n) in the size of the container, while the
previous std::find was O(n) to find the object id.
This avoids behavior quadratic in the number of serialized ids, so it
should speed up saving of big maps.
> SerializedGameData: Use std::set's find for containment check

- src/GameClientPlayer.cpp
Upon erasing an element (and all == true), it would increment the
iterator twice.
Also remove the check against end, which is redundant with the loop
condition.
> Fix iterator error in GameClientPlayer::JobNotWanted

- src/GameClientPlayer.cpp
- src/Ware.cpp
- src/buildings/noBaseBuilding.cpp
- src/buildings/noBuildingSite.cpp
- src/buildings/noBuildingSite.h
- src/buildings/nobBaseWarehouse.cpp
- src/buildings/nobBaseWarehouse.h
- src/buildings/nobHarborBuilding.cpp
- src/buildings/nobHarborBuilding.h
- src/buildings/nobMilitary.cpp
- src/buildings/nobMilitary.h
- src/buildings/nobUsual.cpp
- src/buildings/nobUsual.h
- src/defines.h
- src/figures/nofWarehouseWorker.cpp
- src/nodeObjs/noFlag.cpp
- src/nodeObjs/noFlag.h
- src/nodeObjs/noRoadNode.h
This fixes the problem described in the discussion of #298 where a building site orders to many building materials.
This changes it in a way that those superflous materials are still carried out of the harbour but instantly carried back in. This avoids problems like deleting the Ware in AddWare and accessing it later. This can be caused when Ware->RecalcRoute is called, the ware calls WareDontWantToTravelByShip and this calls AddWare. The caller of RecalcRoute might not be aware of this
Please carefully review this!
Replay: http://www96.zippyshare.com/v/h5ekrbfg/file.html
Save: http://www96.zippyshare.com/v/DVVSu1Vz/file.html
> Fix wrong building material ordering

- src/EventManager.cpp
- src/EventManager.h
- src/GameObject.cpp
This makes the `EventManager` much cleaner through typedefs and better names.
Also fixes 2 issues:
- Memory leaks when calling `Clear` -> List contents must be freed!
- It could happen, that the currently active event gets deleted which destroys the list -> Detect it
It also reduces the includes
> Refactor Eventmanager

- src/GameManager.cpp
- src/defines.h
- src/macros.h
- src/main.cpp
This adds a missing include (according to MS docu) and makes the Debug check run every Game-Cycle and every 128 Heap operations. Using it on every heap op will render the game unusable.
> Fix memory checks

- src/GameClient.cpp
- src/GameClient.h
- src/GameMessages.h
- src/GameProtocol.h
- src/GameServer.cpp
- src/GameServer.h
- src/desktops/dskDirectIP.cpp
- src/desktops/dskHostGame.cpp
- src/desktops/dskHostGame.h
- src/desktops/dskLAN.cpp
- src/desktops/dskLAN.h
- src/desktops/dskLobby.cpp
- src/desktops/dskMultiPlayer.cpp
- src/desktops/dskSelectMap.cpp
- src/desktops/dskSelectMap.h
- src/desktops/dskSinglePlayer.cpp
- src/gameData/LanDiscoveryCfg.cpp
- src/gameData/LanDiscoveryCfg.h
- src/gameTypes/LanGameInfo.cpp
- src/gameTypes/LanGameInfo.h
- src/gameTypes/ServerType.h
- src/ingameWindows/iwDirectIPConnect.cpp
- src/ingameWindows/iwDirectIPConnect.h
- src/ingameWindows/iwDirectIPCreate.cpp
- src/ingameWindows/iwDirectIPCreate.h
- src/main.cpp
Closes #327 
Adds a LAN mode with automatic server discovery through UDP. New desktop is added for the long existing LAN button!
To catch call issues the `ServerType` enum was factored out to a new file, transformed to a boost scoped enum (type safety) and all usages fixed accordingly.
2 Small fixes slipped in: Datatype for lobby list was wrong and passing the host now as a string instead of a char*
Ports are constant and choose right after the regular RTTR ports. Maybe other ports are better?
> Add LAN option

- src/Debug.cpp
- src/Debug.h
- src/FramesInfo.cpp
- src/FramesInfo.h
- src/GameClient.cpp
- src/GameClient.h
- src/GameClientCommands.cpp
- src/GameClientGF_Game.cpp
- src/GameClientGF_Replay.cpp
- src/GameMessageInterface.cpp
- src/GameMessageInterface.h
- src/GameMessages.h
- src/GamePlayerInfo.cpp
- src/GamePlayerInfo.h
- src/GameServer.cpp
- src/GameServer.h
- src/GameServerPlayer.cpp
- src/GameWorldViewer.cpp
- src/helpers/mathFuncs.cpp
- src/helpers/mathFuncs.h
- src/ingameWindows/iwSave.cpp
- src/main.cpp
- src/nodeObjs/noFlag.cpp
Do not merge before
This fixes #315 with a complete overhaul of the network system. The system is analyzed and implemented as described in the new wiki entry I made: https://github.com/Return-To-The-Roots/s25client/wiki/Network-mechanics   
Key issues:
- Server waits for lagging clients and does not continue before (was a possible async cause!)
- Refactored methods: SRP applies: Especially the methods from the server were doing to much to be maintainable. Factored out e.g. NWF and GF handling from the general "do a step" function.
- The ServerDone message is now similar to the GC-Message from the KIs: Clients wont execute a NWF till the Done message is received. Although the Done-Messages could be used for the current NWF they are used for the **next** NWF, just like the GC-Messages to …
> Server fixes

- src/GameSavegame.cpp
- src/SerializedGameData.cpp
- src/SerializedGameData.h
- src/buildings/nobBaseMilitary.cpp
- src/buildings/nobBaseMilitary.h
- src/buildings/nobBaseWarehouse.cpp
- src/buildings/nobMilitary.cpp
- src/figures/nofActiveSoldier.cpp
- src/figures/nofActiveSoldier.h
- src/figures/nofAggressiveDefender.cpp
- src/figures/nofAggressiveDefender.h
- src/figures/nofAttacker.cpp
- src/figures/nofAttacker.h
- src/figures/nofDefender.cpp
- src/figures/nofDefender.h
- src/nodeObjs/noRoadNode.cpp
**DO NOT MERGE**
Please just tell me, if this is ready to merge. As this changes the savegame version and I have 2 other changes that do that too I want to merge all 3 of them at once, so users won't loose their savegames multiple times.
This fixes #355:   
Bug is found. The reason for this is that the system for the AggressiveDefender is completely broken. nofAggressiveDefender::AttackerLost()/nofAttacker::AggressiveDefenderLost should have been used to unlink an attacker from an AggressiveDefender and nofAttacker::LetsFight should have been used to link them. However this is not the case and AttackerLost is never called by anyone.
Bug was introduced here (before git history): http://bazaar.launchpad.net/~flamefire/s25rttr/s25rttr/revision/6559
Normally the defender would have been …
> Fix aggressive defender

- src/GameClient.cpp
- src/GameClient.h
- src/GameClientCommands.cpp
- src/GameClientGF_Game.cpp
- src/GameClientPlayer.cpp
- src/GameClientPlayer.h
- src/GameCommand.cpp
- src/GameCommand.h
- src/GameCommands.cpp
- src/GameCommands.h
- src/GamePlayerInfo.cpp
- src/GamePlayerInfo.h
- src/GameReplay.cpp
- src/GameSavegame.cpp
- src/GameServer.cpp
- src/GameServer.h
- src/GameServerPlayer.cpp
- src/GameServerPlayer.h
- src/GameWorldGame.h
- src/controls/ctrlTable.cpp
- src/desktops/dskGameInterface.cpp
- src/factories/GameCommandFactory.cpp
- src/factories/GameCommandFactory.h
**DO NOT MERGE**
I'll merge this with #370 and #360 as those all change the savegame version
This fixes #357 
It basically replaces the gamecommand for switching with a regular message. As ordering of messages is consistent we know, that after we received the swap from the server all future messages are already swapped. This way no GC-Messages get confused and freeze is fixed.
> Player switch

- src/controls/ctrlChat.cpp
- src/ogl/glArchivItem_Font.cpp
- src/ogl/glArchivItem_Font.h
Now unicode fonts are possible. Fonts can contain all glyphs and lstpacker has been updated to support either unicode-named files or decimal numbered ones. (`U+A12F.player.bmp` or `41263.player.bmp`)
To create extended font files name them `fonX` instead of `fon`
> Add support for extended fonts (unicode)

- src/GameClient.cpp
- src/GameReplay.cpp
- src/GameSavedFile.cpp
- src/GameSavegame.cpp
- src/GameServer.cpp
- src/controls/ctrlEdit.cpp
- src/controls/ctrlEdit.h
- src/desktops/dskDirectIP.cpp
- src/desktops/dskSelectMap.cpp
- src/ingameWindows/iwSave.cpp
- src/ogl/glArchivItem_Font.cpp
- src/ogl/glArchivItem_Font.h
This introduces a new UTF8 library and detects non-UTF8 strings in Font.draw instead of silently doing "something" with them.
Further fixes include minor refactoring for clarity and speed and also conversion S2 map names and authors to UTF-8 before using.
There were also some small bugs in SplitSingleStrings when text was partially drawn and contained newlines
> Utf8 improvements

- src/FramesInfo.h
- src/GameClient.cpp
- src/GameManager.cpp
This allows multiple speed changes during 1 NWF (pressing 'v' multiple times by now only accepts the first one)
It also adds a little number indicating the current speed stepping. Scheme is simple: Show difference to 30 ms in steps of 10 ms with negative (slower) values red and faster ones yellow. Nothing for 30ms and no number for 20ms.
This closes #406
> Speed indicator

- RTTR/texte/de_DE/keyboardlayout.txt
- RTTR/texte/de_DE/readme.txt
- src/GameClient.cpp
- src/TerrainRenderer.cpp
- src/buildings/nobUsual.h
- src/desktops/dskGameInterface.cpp
- src/desktops/dskGameInterface.h
- src/ingameWindows/iwObservate.cpp
- src/ingameWindows/iwObservate.h
- src/ingameWindows/iwSave.cpp
- src/world/GameWorldView.cpp
- src/world/GameWorldView.h
- src/world/GameWorldViewer.cpp
- src/world/GameWorldViewer.h
As request here #425 this implements zooming for observation windows.
Zooming is implemented via an option in `GameWorldViewer` which will call `glScale`.
This also fixes a minor bug, where the cursor in observation windows was not correctly displayed (wrong position)
Zooming the whole game is also possible, although not yet implemented
> Implement zoom for observation windows

- src/GameSavegame.cpp
- src/Pathfinding.cpp
- src/ai/AIInterface.cpp
- src/ai/AIInterface.h
- src/ai/AIJHHelper.cpp
- src/desktops/dskGameInterface.cpp
- src/gameData/TerrainData.cpp
- src/gameData/TerrainData.h
- src/gameTypes/BuildingQuality.h
- src/gameTypes/MapNode.cpp
- src/gameTypes/MapNode.h
- src/world/GameWorld.cpp
- src/world/GameWorldBase.cpp
- src/world/GameWorldBase.h
- src/world/GameWorldGame.cpp
- src/world/GameWorldGame.h
- src/world/GameWorldView.cpp
- src/world/MapLoader.cpp
- src/world/World.cpp
- src/world/World.h
This stores the BQ as a per-field value independent of the current owner. This allows e.g. multiple players on one world, and especially avoids costly recalculation of the BQ by the AI.
Bumps savegame version
Adresses #82 (Prepares #451 which will work upon this)
> Save BQ for all players, not for the current one

- src/desktops/dskGameInterface.cpp
- src/test/CreateSeaWorld.cpp
- src/test/testMap.cpp
This should increase test coverage as the actual BQCalculator functions are tested and not separate instances.
> Don't instantiate new BQCalculator classes in tests

- contrib/backport/boost_1.55-1.56/boost/core/scoped_enum.hpp
- src/SoundEffect.h
- src/gameData/TerrainData.h
- src/gameTypes/ServerType.h
- src/postSystem/PostCategory.h
boost 1.55 has a bug in `boost::native_value()` which this fixes
> fix for scoped enum emulation

- src/SerializedGameData.cpp
- src/buildings/BurnedWarehouse.cpp
- src/buildings/nobBaseWarehouse.cpp
This instance is not registred anywhere. If the game is closed when it is active, it will leak. This puts it into figures (like the fighting)
> Fix mem leak of BurnedWarehouse

- src/GameObject.cpp
- src/GameObject.h
As we don't get a new object, we should not count it. Hence the default assignment operator is ok.
> Don't increment object counter on assignment

- src/desktops/dskGameInterface.cpp
- src/desktops/dskGameInterface.h
- src/gameData/GameConsts.h
- src/gameData/GuiConsts.h
- src/world/GameWorldView.cpp
- src/world/GameWorldView.h
This adds zooming by mouse wheel.
Existing fix states for zoom changed into 50%, 75%, 100%(default), 125% and 150%
These can switched by pressing Z (or Shift-Z in reverse order).
Ctrl+Z resets to default
Magnifying glass in top right now shows zoom percentage (except 100%).
> Zoom by mouse wheel

- src/ai/AIInterface.h
- src/ai/AIPlayerJH.cpp
- src/buildings/nobBaseWarehouse.h
- src/figures/nofScout_Free.cpp
- src/ingameWindows/iwShip.cpp
- src/nodeObjs/noShip.cpp
- src/nodeObjs/noShip.h
- src/test/CreateSeaWorld.cpp
- src/test/CreateSeaWorld.h
- src/test/main.cpp
- src/test/testAttacking.cpp
- src/test/testGameCommands.cpp
- src/test/testSeaAttacking.cpp
- src/test/testSeafaring.cpp
- src/world/GameWorldBase.cpp
- src/world/GameWorldBase.h
- src/world/GameWorldGame.cpp
- src/world/GameWorldGame.h
- src/world/GameWorldViewer.cpp
- src/world/MapLoader.cpp
- src/world/World.cpp
This fixes the non-attackable harbor issue in #550 by starting the coast-search after the critical NW point, which should be ok for almost all maps (except one really tries to cause this bug)
It also makes explorations (ship and scout) correctly honor visible points so they are not explored again.
> Seafaring fixes

- src/ogl/glArchivItem_Font.cpp
- src/test/testFileIO.cpp
In preparation for fixing #618 this checks that everything is UTF8
> More UTF8 filesystem checks

- src/test/testSystem.cpp
Windows only: getEnvVar returns the terminating NULL as part of the string which is wrong
> Fix NULL in getEnvVar

- debian/rules
Looks like it is no longer necessary as it isn't bundled and installed anymore.
> Avoid unnecessary libminiupnp remove

- src/nodeObjs/noSign.cpp
Since the refactoring of noSign.cpp from 02.11. by Flamefire, the geologist places a coal sign instead of a gold sign, if he founds gold.
i assume a misstyping here for the imageId.
> Geologist puts a coal sign instead of gold

- Jenkinsfile
- rttrConfig/files.h
- src/Debug.cpp
- Enables editor
- Removes SDL_opengl on editor
- Use typename on clang
@Flow86 Could you tell me, what happens with clang when you don't use `typename`? Haven't seen a failure yet.
> Another try on compile fixes

- rttrConfig/files.h
- src/Debug.cpp
- src/network/GameClient.h
- src/test/testBuilding.cpp
- src/test/testLua.cpp
Fix the endian dependency of the editor and remove the `typename` for clang
> Compile fixes

- .travis.yml
- src/Replay.cpp
- src/SavedFile.cpp
- src/Savegame.cpp
- src/network/GameClient.cpp
- src/network/GameServer.cpp
Background: When you connect, the server sends you map-meta-data (name, size). The client checks if it is already in <cfgDir aka .s25rttr>/MAPS  (played maps folder) and if yes, send the checksum of to the server. If  no or the checksum mismatches the server sends the map compressed with  bz2. Once received it is uncompressed which seems to fail with '-8'  which means 'output buffer to small'. This does not make sense, because  that map was just compressed by the server and the size send to the  client. 
This happens when saving a  game, loading that, saving to the same name and trying to load that  again. This shows a bug in the above algorithm. A file with the same name exists but is smaller then the wanted one. Bug 1 overwrites the size sent by the server and Bug 2 does not handle …
>  Fix invalid savegame after second load-save-cycle 

- src/Loader.cpp
- src/desktops/dskTest.cpp
- src/desktops/dskTest.h
This finally fixes #532 as it adds non-transparent bitmaps to the supported formats.
Basically: When loading a palette the transparent color index is set to the pink, if it is found, or 0 if it is not. That index is then used to determine if a pixel is transparent when converted to ARGB.
It is also possible to disable transparency completely with a method in the palette. The transparent index will then become the background color used when loading/drawing transparent images on it.
When loading a LBM (textures and load screens) the transparent color is set as specified in the file format or removed if it isn't set. For TEX*.LBMs we use a fixed index of 0 which is the one used in S2 (but BB didn't bother to write that to the file header)
This solves broken load screens and possible …
>  Fix transparency issues with Loading screens 

- release/bin/macos/rttr.command
- release/bin/rttr.sh
- src/BasePlayerInfo.cpp
- src/BuildingRegister.cpp
- src/BuildingRegister.h
- src/GamePlayer.cpp
- src/JoinPlayerInfo.cpp
- src/SerializedGameData.cpp
- src/SerializedGameData.h
- src/desktops/dskTest.cpp
- src/desktops/dskTest.h
- src/figures/nofAttacker.cpp
- src/figures/nofTradeDonkey.cpp
- src/gameData/LanDiscoveryCfg.cpp
- src/network/GameMessages.h
- src/nodeObjs/noShip.cpp
- src/random/Random.cpp
- src/test/testSerialization.cpp
- src/world/GameWorld.cpp
Fixes the issue reported in #775 which makes some savegames crash after loading.
Further improves start scripts (especially MacOSX) and introduce a variable length uint32_t serialization which saves file size for short strings
> Savegame fixes

- src/lua/LuaInterfaceBase.cpp
Fixes #777 
@Flow86 Could you check the mygettext implementation changes?
Basically the problem was: We set LC_ALL to the locale and use the result of `setLocale` to select a catalogue. If the system configuration is not unique (e.g. `LC_CTYPE=en_US.UTF-8;LC_NUMERIC=de_DE.UTF-8;LC_TIME=de_DE.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=de_DE.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=de_DE.UTF-8;LC_NAME=de_DE.UTF-8;LC_ADDRESS=de_DE.UTF-8;LC_TELEPHONE=de_DE.UTF-8;LC_MEASUREMENT=de_DE.UTF-8;LC_IDENTIFICATION=de_DE.UTF-8`) then we don't get a single language back.
This uses Boost.Locale to parse and pick the language configuration which is much more robust.
Besides that: We should use standard locations for language files (`de_DE/LC_MESSAGES/rttr.mo`) and probably simply use gettext or Boost.Locale …
> Fix localization if system has multiple configurations

- src/Game.cpp
- src/Game.h
- src/GamePlayer.cpp
- src/GamePlayer.h
- src/SerializedGameData.cpp
- src/SerializedGameData.h
- src/ai/AIPlayer.h
- src/lua/LuaInterfaceGame.cpp
- src/lua/LuaInterfaceGame.h
- src/lua/LuaPlayer.cpp
- src/lua/LuaPlayer.h
- src/network/CreateServerInfo.h
- src/network/GameClient.cpp
- src/test/GameWithLuaAccess.h
- src/test/GameWorldWithLuaAccess.h
- src/test/WorldFixture.h
- src/test/testBuilding.cpp
- src/test/testLua.cpp
- src/test/testLuaGUI.cpp
- src/test/testSerialization.cpp
- src/world/GameWorld.cpp
- src/world/GameWorld.h
- src/world/GameWorldBase.cpp
- src/world/GameWorldBase.h
This commit adds the logic discussed in issue #517, that the ai will accept cancel requests.
In addition i have added basic checks for the pact state and the possibility to suggest a pact to the player.
I skipped the implementation for accepting or starting a cancel request by AI, because i had some problems with finding a GameCommandFactory (i guess im missing this), which is usable for this intent.
But despite that, i am creating this pull request, cause it resolves the discussed logic from issue #517.
> AI will accept pact cancel & basic lua interface

- src/figures/nofTradeDonkey.h
- src/figures/nofTradeLeader.cpp
- src/test/testTrading.cpp
I have added a simple PostMsg when a trade leader arrives in a ware house.
If this PR will be merged before #792, named PR has to add a patch to change the figure calculation for the trade leader (helpers -> scout).
If it will be merged after named PR, this test case has to be adjusted.
> Added Trade-Message if caravan leader arrives.

- src/desktops/dskGameInterface.cpp
In issue #801 its documented, that replays do not work.
After some debugging i realized that the issue is in dskGameInterface line 323. In this code block the snails for lagging players are drawn. But in a replay the variable nwfInfo is null.
So i added an else clause, to display replay info in replay mode and otherwise the snails may be drawn.
> Do not display Snails in Replays 

- src/GlobalGameSettings.cpp
- src/addons/AddonFrontierDistanceReachable.h
- src/addons/Addons.h
- src/addons/const_addons.h
- src/buildings/nobBaseMilitary.cpp
- src/buildings/nobMilitary.cpp
- src/buildings/nobMilitary.h
- src/pathfinding/FindPathReachable.cpp
- src/pathfinding/FindPathReachable.h
- src/pathfinding/PathConditionReachable.h
- src/test/testFrontierDistance.cpp
This addon enables a check for frontier distance calculation. If this addon is enabled, a human path as to be within the triple distance length between both military buildings.
If the distance between both buildings is less then 10, the calculation base will a distance of 30 (maybe this value is a bit high?)
I hope that this "calculation" some how fits the request (#206).
@Flamefire: is there any test case for those frontier logic?
> Added Addon FrontierDistanceReachable

- src/GlobalGameSettings.cpp
- src/addons/AddonCoinsCapturedBld.h
- src/addons/Addons.h
- src/addons/const_addons.h
- src/buildings/nobMilitary.cpp
- src/test/testAttacking.cpp
I have added a new addon to the game which takes over the control of coin order for captured buildings. This feature was requested by #388.
For unit testing i have added 2 new test cases to testAttacking, because it somehow plays into that.
i have copied the ConquerBld - test case and removed everything not related / unneeded for my test case. i hope that you are okay with that.
if you have any improvements, i will try to include them.
> Added new addon to control the coin order for captured military buildings

- src/ingameWindows/iwObservate.cpp
I tried to compile it with **clang** compiler and had this error:
...
[ 62%] Building CXX object src/CMakeFiles/s25Main.dir/ingameWindows/iwMsgbox.cpp.o
[ 62%] Building CXX object src/CMakeFiles/s25Main.dir/ingameWindows/iwMusicPlayer.cpp.o
[ 62%] Building CXX object src/CMakeFiles/s25Main.dir/ingameWindows/iwObservate.cpp.o
/home/goiko/s25client/src/ingameWindows/iwObservate.cpp:37:14: error: unused
variable 'SmallWndSize' [-Werror,-Wunused-const-variable]
const Extent SmallWndSize(260, 190);
^
/home/goiko/s25client/src/ingameWindows/iwObservate.cpp:38:14: error: unused
variable 'MediumWndSize' [-Werror,-Wunused-const-variable]
const Extent MediumWndSize(300, 250);
^
/home/goiko/s25client/src/ingameWindows/iwObservate.cpp:39:14: error: unused
variable 'BigWndSize' …
> Fix unused variable errors

- src/desktops/dskGameInterface.cpp
- src/ingameWindows/iwPostWindow.cpp
- src/world/GameWorldGame.cpp
- src/world/GameWorldGame.h
- src/world/GameWorldView.cpp
- src/world/GameWorldViewer.cpp
- src/world/World.cpp
- src/world/World.h
Since there seems no work on #681 i have picked up the changes on the glyph rendering and applied the requested changes.
Also i have combined the evaluation if a direction targets a flag (which was used 3 times in the code block).
The changes related to saving i have skipped, because someone else already added a similar logic.
As i found it is a good idea: i also included the change to enable backspace for post message deletion for macs.
@Flamefire  if you have any improvements left, i would be willing to apply them.
> Continue for #681 (Show direction glyph toward flag halfway out)

- src/buildings/nobBaseWarehouse.cpp
Move soldiers from reserve back to inventory, if the warehouse is getting destroyed.
fixes #839
> Re-Add Reserve soldiers to inventory if Warehouse gets destroyed

- src/mapGenerator/RandomMapGenerator.cpp
As the humidity check and mountains exclude each other, it has to be a mistake to check it here.
See my comment in #842  as reference. 
I also removed the first if check for placing fish, as it is useless from logical perspective, as it will always return true, if the the second is true, also its excluding the later else-clauses (as water is not vital or mineable).
> Remove Humidity Check from placing resources on mineable terrain.

- src/controls/ctrlButton.cpp
- src/controls/ctrlTextButton.cpp
Closes #888 
It uses the font color as suggested and brings the texture color closer to the suggestion: 
The complete match is not possible as we colorize a colored texture where the original uses completely other colors (grey in this case) So we can basically just make it slightly darker or lighter
> Improve colors for disabled buttons

- src/GamePlayer.cpp
- src/test/testRegressions.cpp
The bug in #913 was caused by destroying the HQ first (which triggers a defeat check) and then the military building (semi-random: depends on positions on the map). The latter did not trigger a defeat check and hence the map was not made visible as the game did not know that the player was defeated
> Test also for defeat when a military building was destroyed

- src/ingameWindows/iwMinimap.cpp
Fixes bug appearing when minimizing or maximizing minimap (title bar enlarges every time window is minimized). I am unsure if it's the best way to do so.
> Fix minimize minimap enlarging window

- driver/include/driver/MouseCoords.h
- driver/src/VideoDriver.cpp
- driver/video/SDL/src/VideoSDL.cpp
- driver/video/SDL2/VideoSDL2.cpp
- driver/video/WinAPI/src/WinAPI.cpp
- src/GameManager.cpp
- src/GameManager.h
- src/Settings.cpp
- src/Settings.h
- src/WindowManager.cpp
- src/WindowManager.h
- src/controls/ctrlList.cpp
- src/controls/ctrlProgress.cpp
- src/controls/ctrlScrollBar.cpp
- src/controls/ctrlTable.cpp
- src/desktops/dskGameInterface.cpp
- src/desktops/dskGameInterface.h
- src/desktops/dskGameLoader.cpp
- src/test/mockupDrivers/MockupVideoDriver.cpp
- src/test/mockupDrivers/MockupVideoDriver.h
- src/test/testBuilding.cpp
- src/test/testBuildingProps.cpp
- src/test/testDskGameInterface.cpp
Minor refactoring to make Code more testable.
Keep cursor scoll image while scrolling
Test those for all cases:
- Regular
- Left click cancels it
- Opening/closing window does not cancel scrolling unless it is modal
- Scolling in road mode, at end of scroll you are still in road mode
- Ctrl+leftclick scrolls, left-up cancels
@Spikeone To keep scrolling when opening a window I wanted to stay true to the S2 behaviour but that is inconsistent:
- Opening a (ingame) window makes it "active" (visible on title bar)
- But you keep scrolling -> Background is actually active
- For this I don't make the background(desktop) inactive while scrolling, so desktop AND window is active
- This way input (key,mouse) goes to the desktop not the window and this works
But now we have 2 active "windows" which I …
> Fix cursor image while scrolling

- README.md
- shell.nix
This PR give an easy way to get a working environnement on this project without polluting his system-side installation with uneeded packages (sdl, miniupnpc, ...).
Insteed of installing all the prerequesites, the only requirement is having `nix` installed. Then, in s25client, just open `nix-shell`. This works on both Linux and Darwin/MacOSX.
> Add shell.nix

- libs/s25main/GamePlayer.cpp
- libs/s25main/buildings/nobUsual.cpp
The assertion is unsafe at this point, even though it might
appear logical. The reason it is unsafe is that it is called from
nobShipYard::nobShipYard (the consturctor) indirectly through the
constructor nobUsual::nobUsual (constructor of the base class).
The dynamic_cast<nobShipYard*> then becomes undefined behaviour,
because the constructor of nobShipYard has not started to run on
the workplace object; it is still running the nobUsual
constructor.
See also https://stackoverflow.com/a/6299463/1248008
Fixes #1048.
> Fix Undefined Behaviour / RTTR_Assert triggering in nofShipWright

- .travis.yml
Build may otherwise fail with "Your Homebrew is outdated. Please run brew update"
Fixes failure of #1067
> Update Homebrew on travis

- libs/common/include/helpers/MultiArray.h
- libs/s25main/GamePlayer.cpp
- libs/s25main/buildings/nobBaseWarehouse.cpp
- tests/s25Main/integration/testBaseWarehouse.cpp
- tests/s25Main/integration/testHarbor.cpp
Fix crash when destroying harbor with an ordered builder for an expedition
When ordering a builder it is assumed that it is put into the jobsWanted
list which does not happen if the builder can be sent right away. On
destruction the jobWanted is not found and the end-iterator is passed to
list::erase which leads to corruption of the list.
> Fix harbor crash

- libs/common/include/helpers/containerUtils.h
- libs/s25main/drivers/VideoDriverWrapper.cpp
- tests/common/testContainerUtils.cpp
- tests/s25Main/UI/testVideoDriver.cpp
When the textures stored in LOADER are destroyed the videodriver was
already shut down so the OGL library might already be unloaded. An
access to glDeleteTextures will then result in an AV.
Fix: Check if textures are already freed and don't free again.
> Fix crash on close

- cmake/optimizations.cmake
Fixes semicritical bug leading to #1094 in which flags were ignored when added with `CheckAndAddFlags`
Fixes #1094
> Fix tune flags

- libs/s25main/WindowManager.cpp
Have to flip the image before saving it as OpenGL has the image "upsidedown"
> Fix screenshot

- tests/libsamplerate_cpp/testSamplerate.cpp
- tests/s25Main/UI/testSmartBitmap.cpp
- tests/s25Main/UI/testVideoDriver.cpp
On 0.1.9 returning NULL as the data pointer is not allowed even if the
size is zero and the pointer never used.
Fixes #1090
> Fix Samplerate tests

- tests/common/testPoint.cpp
Compare x,y separately to actually use the tolerance based comparison of boost. While it would be possible to implement it for Point<T> it requires the operations that are just tested in that file, hence we need to test the underlying values directly.
Run the test a couple thousand times to make sure there are no more failures using Clang 8&9 by `ctest -R common --output-on-failure -quiet --repeat-until-fail 1000000`
Fixes https://github.com/Return-To-The-Roots/s25client/issues/1136
> Fix spurious failures in unscale_point test

- libs/common/src/RTTR_Assert.cpp
- libs/s25client/s25client.cpp
- libs/s25main/Messenger.cpp
- libs/s25main/controls/ctrlChat.cpp
- libs/s25main/controls/ctrlEdit.cpp
- libs/s25main/controls/ctrlEdit.h
- tests/s25Main/UI/testControls.cpp
- tests/s25Main/lua/testLua.cpp
The LOG class expects a format string, so do not pass a user-provided string to it which may or may not contain a format specifier/special char.
Also fix misbehaving edit on clearing where the internal string was not kept in sync with the actual text so clearing it still showed the old text.
> Fix crash on chat input of format strings

- libs/s25main/ingameWindows/iwMapGenerator.cpp
This changes the texture of the back button in the mapgenerator settings window to the default red used for all buttons. Fixes #985
> Update MapGenerator back button texture, fixes #985

- libs/s25main/controls/ctrlEdit.cpp
- libs/s25main/controls/ctrlEdit.h
- libs/s25main/ingameWindows/iwLobbyConnect.cpp
- libs/s25main/ingameWindows/iwLobbyConnect.h
This will store the password as a hash only in the INI file instead of in plaintext.
On reading this will be detected and the password field will be filled in with the hash instead. This results in 32 stars (*) showing, but IMO this is OK. Otherwise we would need a flag to change when the edit changed or risk false positives (user pw detected as hash although it is a plain text pw)
Additionally I implemented TAB in addition to ENTER to switch between fields in that dialog as this is what I'm always trying to use :/
> Store password as hash

- .travis.yml
- README.md
This adds the `git lfs` commands to the readme and travis
It also updates the travis badge still pointing to travis.org instead of travis.com
> Fix build on travis and update readme

- libs/common/include/Point.h
This fixes 2 bugs in the editor reported by @Spikeone 
The Point changes are required for Wnoexcept warning supression (and are correct)
> Fix some editor bugs

- libs/s25main/Playlist.cpp
i've got a loading error in Playlist.cpp on my machine. I traced the fault down to Playlist loading with my environment's locale. My suggested fix is to apply "C" locale before starting to parse.
Before applying this patch, it should refuse loading by running
`LC_ALL=nb_NO.UTF-8 bin/s25client`
while running
`LC_ALL=C bin/s25client`
successfully loads
> set locale before parsing playlist

- libs/s25main/controls/ctrlPreviewMinimap.cpp
- libs/s25main/controls/ctrlTable.cpp
- libs/s25main/controls/ctrlTable.h
- libs/s25main/desktops/dskLAN.cpp
- libs/s25main/desktops/dskLobby.cpp
- libs/s25main/desktops/dskSelectMap.cpp
- libs/s25main/desktops/dskSelectMap.h
- libs/s25main/ingameWindows/iwPlayReplay.cpp
- libs/s25main/ingameWindows/iwSave.cpp
- tests/s25Main/UI/testControls.cpp
As explained in https://github.com/Return-To-The-Roots/s25client/issues/1243#issuecomment-636804549 this fixes #1243 by showing an error in the log for completely broken maps (e.g. wrong file format) and a message box when selecting an unsupported map.
To avoid this triggering without the user selecting anything (e.g. when there is only 1 map in a folder) I changed it so no map is selected when changing "folders"
Also some related fixes and refactoring:
- When no map was selected it was still drawn with size zero
- ctrlTable: Sorting behavior has now a better interface instead of some strange bool pointer
I have no idea how to unittest the dskSelectMap but did add some tests for table sorting
> Map load error handling

- libs/libGamedata/lua/GameDataLoader.cpp
- tests/libGameData/testGameData.cpp
- tests/testHelpers/rttr/test/TmpFolder.hpp
This is in preparation for syncing gameData files and adds some restrictions:
- file names must be alpha-numeric + underscore
- they must be relative to current file and not leave the gameData base folder
- they must have `.lua` as the extension
This should be a good barrier to avoid arbitrary file inclusion but it should be evaluated if there are other issues when executing untrusted lua code. @Spikeone  ideas? Anything network or filesystem in lua which is currently possible?
> Add more restrictions to gameData loading and test them

- data/RTTR/sound.scs
- libs/s25client/CMakeLists.txt
- libs/s25client/commands.cpp
- libs/s25client/commands.h
- libs/s25client/s25client.cpp
- libs/s25main/Loader.cpp
- libs/s25main/convertSounds.cpp
- libs/s25main/convertSounds.h
Use the new loadMapping function from libsiedler2 and adapt the conversion script
Found also a bug: It used the wave header instead of sound.scs for getting the source samplerate.
To help with improving the sounds I added a command line switch `--convert-sounds` which converts the sounds into wave files into `convertedSoundEffects` inside the user settings folder
> Improve sound conversion

- libs/common/include/helpers/mathFuncs.h
- libs/s25main/convertSounds.cpp
- tests/common/testMathHelpers.cpp
From discussion here: https://github.com/Return-To-The-Roots/s25client/pull/1258/files#r439767352
This makes it clear that the values are correct
> Make WAV header calculation more explicit

- libs/common/include/helpers/EnumRange.h
- libs/s25main/buildings/nobBaseWarehouse.cpp
- libs/s25main/buildings/nobBaseWarehouse.h
- libs/s25main/ingameWindows/iwHQ.cpp
- tests/common/testEnumRange.cpp
- tests/s25Main/integration/testGameCommands.cpp
- tests/s25Main/lua/testLua.cpp
Also don't touch claimed reserve soldiers
Fixes #1253
> Update player inventory with reserve soldiers used on ClearResources

- CMakeLists.txt
- libs/libGamedata/lua/LuaInterfaceBase.cpp
Updates Boost.Nowide to 11.0 and adds some missing includes. Seems MSVC got more careful with including stuff in their std headers
@Flow86 Please merge once passed, other changes likely need to be based on this
> Fix building on recent MSVC (missing includes)

- libs/s25main/ai/aijh/AIConstruction.cpp
- libs/s25main/ai/aijh/AIPlayerJH.cpp
- libs/s25main/ai/aijh/AIPlayerJH.h
- libs/s25main/ingameWindows/iwMapDebug.cpp
- tests/s25Main/integration/testAI.cpp
Found a regression caused by the previous fix: Setting a flag in distance 2 of the border disallows placing a flag next to the border but doesn't change it's underlying BQ. Previously a changed BQ lead to reevaluation of neighbor BQs via recursive calls which was removed to avoid excessive recalculations when not required but missed the above case. Hence add distance-1-nodes for changed BQs in the event
Also some refactoring to reuse the code in the map debug window and in the test to reproduce this by brute-force setting flags all over the players territory. This also didn't occur previously in the test because if the BQ in the border-neighbour node was castle, placing a flag changed it to BigBuilding hiding the issue. Hence place some trees to reduce BQ to less-than castle in many …
> Fix AI BQ update when placing flag near border

- libs/s25main/Loader.h
- libs/s25main/SerializedGameData.cpp
- libs/s25main/SerializedGameData.h
- libs/s25main/figures/nofBuildingWorker.cpp
- libs/s25main/figures/nofBuildingWorker.h
- libs/s25main/figures/nofHunter.cpp
- libs/s25main/figures/nofHunter.h
- libs/s25main/ogl/glArchivItem_Bitmap_Player.cpp
- libs/s25main/ogl/glArchivItem_Bitmap_Player.h
When the hunter arrived at the shooting pos but the animal was not yet
ready, the hunter was still drawn as "walking" making it walk past its
destination point (due to interpolation using the "wait" event) and
warped back once the animal was ready.
This also triggered an assertion checking for walking draw while not
walking
Fixes #1126
> Fix visual glitch when hunter is waiting for the animal

- tests/s25client/CMakeLists.txt
The existing regular expression seems to expect that the test will
only ever be run from a git checkout. Gentoo would like to eventually
run it from a release source tarball.
> Allow dot in showVersion test

- tools/ci/jenkins/build.sh
Without mapping /etc/passwd too changing the docker user (done by Jenkins) doesn't pass in the remaining information (name, shell, ...)
The tests require $USER to be set, so do that manually in case it isn't set
> [CI] Set $USER on Jenkins

- libs/s25main/Window.cpp
As the title says, the addon options window has a bug where you can click through a combo box list item and also select the option below. This commit fixes this by not only locking the list region for the parent of the list, but recursively for all parents.
> Fix a click through bug for combobox lists in addon window

- libs/s25main/network/GameClient.cpp
Most simple implementation to avoid #1319 where actual simulation time will be lower than real time due to incrementing it essentially in chunks (similar to/of) VSync time.
This works for cases where the GF length is larger than the execution time for 1 GF + drawing and related.
This is only intermediate until we implement something better, see #1319, but improves the situation already. Similar to https://github.com/JonathanSteinbuch/s25client/commit/536a64fb9f83d55f1a4e5f0ce66ef052b3bbf5c1
> Fix client-side time synchronisation for simple cases

- libs/s25main/Window.cpp
- libs/s25main/controls/ctrlTimer.cpp
- libs/s25main/controls/ctrlTimer.h
- libs/s25main/desktops/dskCredits.cpp
- libs/s25main/desktops/dskCredits.h
- libs/s25main/desktops/dskGameLoader.cpp
- libs/s25main/ingameWindows/iwMapDebug.cpp
This uses a `Timer` in the ctrlTimer and explicit chrono units.
Then refactors the credits screen to make use of timers instead of hand-rolled timing.
It also fixes a bug introduced in the resources PR where the "credits" resource wasn't loaded so the pictures were missing
> Refactor credits window and timer control

- libs/s25main/SerializedGameData.cpp
- libs/s25main/gameTypes/GO_Type.h
Prior save games used 2 Bytes instead of 1 (while 1 would have been enough)
Fixes #1328
@Flow86 This is urgent as all savegames saved with the current nightly can't be loaded while the current nightly can't load older ones.
> Fix wrong type for GO_Type enum

- libs/s25main/ingameWindows/iwMsgbox.cpp
Fixes a newly introduced bug where the results from a message box button click where wrongly registered.
ID_BT_0 was added twice as it is also added in AddButton itself.
> Fix message box window button id bug

- libs/s25main/mapGenerator/Algorithms.h
- libs/s25main/mapGenerator/HeadQuarters.h
- libs/s25main/mapGenerator/Map.cpp
- libs/s25main/mapGenerator/Map.h
- libs/s25main/mapGenerator/RandomMap.cpp
- libs/s25main/mapGenerator/Resources.cpp
- libs/s25main/mapGenerator/Terrain.cpp
- libs/s25main/mapGenerator/Terrain.h
- tests/s25Main/mapGenerator/testAlgorithms.cpp
- tests/s25Main/mapGenerator/testTerrain.cpp
By replacing std::vector to std::set to boost helper::contains (log(n) vs. log(O(n)) random maps of size 1024 x 1024 are now generated in less than 25% of the time (40s vs. 8s). Thanks @JonathanSteinbuch !
> Performance boost for random map generation

- libs/s25main/mapGenerator/Rivers.cpp
- libs/s25main/mapGenerator/TextureHelper.cpp
- tests/s25Main/mapGenerator/testRivers.cpp
Rivers should end at sea level (= minimum height of the map after ResetSeaLevel). This make avoids rivers from a main island to "swap" over to another island which looks a bit odd.
> Rivers should end when going into sea or lakes

- libs/s25main/Game.cpp
- libs/s25main/controls/ctrlTable.cpp
- libs/s25main/controls/ctrlTable.h
- libs/s25main/desktops/dskGameInterface.cpp
- libs/s25main/gameData/GameConsts.h
- libs/s25main/ingameWindows/iwPlayReplay.cpp
- libs/s25main/ingameWindows/iwPostWindow.cpp
- libs/s25main/ingameWindows/iwSave.cpp
- libs/s25main/network/GameClient.cpp
- libs/s25main/network/GameServer.cpp
This addresses issue #1317 
Although there was no consensus on which speed to base ingame time there was a consensus that it should be consistent and without reference to game frames.
So as a preliminary solution I changed every time representation based on the assumption of normal speed. 
In the save dialog, the playReplay window and the post window in particular that meant changing GFs to time. 
The only thing that maybe looks a bit silly is the autosave pulldown, because I didn't change the intervals (should I?):
Note: I didn't remove the display of GFs in the debug line at the top and for jumping/skipping as they are mostly debug/expert features
> Base ingame times on normal speed

- libs/s25main/ingameWindows/iwMapGenerator.cpp
- libs/s25main/mapGenerator/HeadQuarters.cpp
- libs/s25main/mapGenerator/HeadQuarters.h
- libs/s25main/mapGenerator/Map.cpp
- libs/s25main/mapGenerator/MapSettings.h
- libs/s25main/mapGenerator/NodeMapUtilities.h
- libs/s25main/mapGenerator/RandomMap.cpp
- tests/s25Main/mapGenerator/testHeadQuarters.cpp
- tests/s25Main/mapGenerator/testResources.cpp
Hi guys, 
This is basically a new feature for random maps to consider the distance of HQs to mountains for HQ placement. That should generate more competitive maps with fairer HQs. Also added a configuration option to specify how fair away players should be positioned. Also, I hope the coed & comment changes make the workflow of `FindHqPositions` easier to follow!
Example map - mountain distance "close":
Example map - mountain distance "far":
Let me know if you have any suggestions for improvement!
> HQ positions on random maps consider mountain distance

- libs/s25main/mapGenerator/Islands.cpp
- libs/s25main/mapGenerator/RandomMap.cpp
- libs/s25main/mapGenerator/RandomMap.h
**Current state**
The center of each player island is calculated by finding the `MapPoint` with the greatest distance to any land. Therefore, the first island depends only on the distance to the center island (which is not populated by any HQ). There are usually multiple points with equal distance to the center island. Therefore the algorithm chooses the first one starting from `x=0/y=0` and iterating through the points with the maximum distance like a standard iteration over the map (`x=0,1,2,...width-1` etc.). That usually leads to the first island (blue player) being placed in the top-right corner of the map. Other players' islands are similar predictable. 
**Suggested improvement**
Choose a minimum distance of every island-center to any land. Then randomly choose one of the …
> Improve island generation on random water maps

- .github/workflows/unit-tests.yml
- CMakeLists.txt
- libs/common/include/Point.h
- libs/libGamedata/gameData/DescIdx.h
- libs/s25client/s25client.cpp
- libs/s25main/animation/MoveAnimation.cpp
- tests/common/testPoint.cpp
I reduced the repetition of the Point class by using the preprocessor to stamp out the arithmetic functions. Adding of `noexcept` should also help and avoid the compiler warning from #1358
I also validated the codegen on godbolt for GCC, Clang and MSVC to be optimal (as-if handwritten)
> Add noexcept specifications to Point and DescIdx and modernize Point.h 

- CMakeLists.txt
- libs/s25main/ai/AIInterface.cpp
- libs/s25main/ai/AIInterface.h
- libs/s25main/ai/AIResource.h
- libs/s25main/ai/aijh/AIConstruction.cpp
- libs/s25main/ai/aijh/AIMap.h
- libs/s25main/ai/aijh/AIPlayerJH.cpp
- libs/s25main/ai/aijh/AIPlayerJH.h
- libs/s25main/ai/aijh/AIResourceMap.cpp
- libs/s25main/ai/aijh/AIResourceMap.h
- libs/s25main/gameTypes/GameTypesOutput.h
- tests/s25Main/lua/GameWithLuaAccess.h
- tests/s25Main/simple/testGameTypes.cpp
The current AI didn't know about inexhaustible granite mines and fish
I also started changing the resourceMaps array to an EnumArray which lead to a bunch of related changes by introducing separate enums for surface, subsurface, and node resources which makes the intention clearer:
- AIResource is what the AI cares about
- Surface and SubSurface resources are the ones from AIResource which are above/below the surface and includes `Nothing` (the enums aren't contiguous so can't use OptionalEnum)
- AINodeResource is all AIResources + a few special ones like "blocked" and "multiple". I kept this during refactoring but might remove later as the aiMap.res entries aren't updated so they become out of date fast. Might fix that later or remove
Most importantly I merged the resource rating …
> Refactor AI and teach it about unlimitted resources

- README.md
- codecov.yml
See https://docs.codecov.io/docs/ignoring-paths
Let's let this run and check that reported coverage roughly matches between coveralls and codecov
> Fix codecov yml exclusion

- libs/s25main/buildings/nobBaseWarehouse.cpp
- libs/s25main/buildings/nobBaseWarehouse.h
- libs/s25main/desktops/dskGameInterface.cpp
- libs/s25main/ingameWindows/IngameWindow.h
- libs/s25main/ingameWindows/TransmitSettingsIgwAdapter.cpp
- libs/s25main/ingameWindows/TransmitSettingsIgwAdapter.h
- libs/s25main/ingameWindows/TransmittingSettingsWindow.cpp
- libs/s25main/ingameWindows/TransmittingSettingsWindow.h
- libs/s25main/ingameWindows/iwAction.cpp
- libs/s25main/ingameWindows/iwAction.h
- libs/s25main/ingameWindows/iwBuildOrder.cpp
- libs/s25main/ingameWindows/iwBuildOrder.h
- libs/s25main/ingameWindows/iwDemolishBuilding.cpp
- libs/s25main/ingameWindows/iwDiplomacy.cpp
- libs/s25main/ingameWindows/iwDistribution.cpp
- libs/s25main/ingameWindows/iwDistribution.h
- libs/s25main/ingameWindows/iwHQ.cpp
- libs/s25main/ingameWindows/iwMilitary.cpp
- libs/s25main/ingameWindows/iwMilitary.h
- libs/s25main/ingameWindows/iwPostWindow.cpp
- libs/s25main/ingameWindows/iwShip.cpp
- libs/s25main/ingameWindows/iwSurrender.cpp
- libs/s25main/ingameWindows/iwTools.cpp
- libs/s25main/ingameWindows/iwTools.h
- libs/s25main/ingameWindows/iwTrade.cpp
- libs/s25main/ingameWindows/iwTransport.cpp
- libs/s25main/ingameWindows/iwTransport.h
- libs/s25main/network/GameClient.cpp
Hello there,
Pauses have some weird problems. Most notably when you are in the process of building a road when you pause the game then you can click to finish the road and this leaves an unremovable ghost road as seen below.
Another problem is that for many ingame settings windows if you change something during a pause the changes very often are not registered, but still displayed. In the above picture this is visible for the military window, where the number of soldiers in barracks, even after the pause, does not reflect the choice made during the pause.
To address these issues I propose the changes in this pull request.
The guiding principles that I used are as follows (I tried to stay close to the ideas used already in the code and the things decided in some issues):
1. Most …
> Fix some problems with unexpected behaviour during and after pauses

- libs/s25main/ingameWindows/iwMapGenerator.cpp
- libs/s25main/ingameWindows/iwMapGenerator.h
- libs/s25main/mapGenerator/Islands.cpp
- libs/s25main/mapGenerator/Islands.h
- libs/s25main/mapGenerator/MapSettings.h
- libs/s25main/mapGenerator/RandomMap.cpp
- libs/s25main/mapGenerator/RandomMap.h
- tests/s25Main/UI/testIngameWindow.cpp
- tests/s25Main/mapGenerator/testIslands.cpp
- tests/s25Main/mapGenerator/testRandomMap.cpp
First, I fixed the size of players' home islands to a value depending on the map size (200-1200 nodes). Also, I added configurable "extra" islands (few/medium/many) of random size (range between 200 & 1200 nodes). This makes water & mixed maps slightly more interesting to play I think.
At the moment, I did not bind the central island to a specific size. I liked the idea of having a big island where multiple players can meet eventually. But up to discussion, could also make it optional/configurable as well. 
Also, I have to increase the test coverage, I'll look at that this weekend.
> Configurable number of islands for water & mixed maps

- libs/s25client/s25client.cpp
- libs/s25main/Debug.cpp
- libs/s25main/Debug.h
May show the exception from #1374
This also takes care not to let any exception escape from the exception handlers
> Handle more exceptions in the program

- libs/s25main/mapGenerator/Resources.cpp
The random map generator placed resources purely random in a mountain. This is
not great. Manual maps always cluster resources and we should do so too.
However, having all resources in every mountain is also a good thing for
the balance of the game so we want to keep the clusters small. This is a
try to build small clusters while keeping the ratios the same.
With this patch, mountains (default distribution) look like this:
> Cluster mineable resources in random maps

- README.md
Followup of https://github.com/Return-To-The-Roots/s25client/commit/19e2690f035ebeda110f9aa23eaba5b3a6c58b61
> Update boost version in build documentation

- README.md
Followup of https://github.com/Return-To-The-Roots/s25client/commit/99207edef86830f66193d312e68e25cf441fe8cf.
> Update Lua version in build documentation 

- CMakeLists.txt
This avoids a misleading message about why later versions are incompatible, e.g.: 'found suitable version "11.1.0", minimum required is "10"'
Fixes #1400
> Explicitely set the clang-format version to EXACT

- libs/s25main/ai/aijh/AIPlayerJH.cpp
As mentioned on the forums and in an issue (fixes #1084), AI tended to build wrong tools. To investigate, I privately added logging corresponding to the commented tools in `AIPlayerJH.cpp` `AdjustSettings`:
https://github.com/Return-To-The-Roots/s25client/blob/85a6b994185edbe1479462efc640abcc9a048fb9/libs/s25main/ai/aijh/AIPlayerJH.cpp#L2364-L2368
Running a game observing this logging, then saving the game and returning as one of the AIs, I saw they set up their tools wrong.
I found the order in `ToolConsts.h` matched the order of the ingame interface, but the indexes used in `AIPlayerJH.cpp` did not match this - as you can see, `GoodType::Saw` would be index 3 here, while above `toolsettings[2]` is commented as `Saw`.
https://github.com/Return-To-The-Roots/s25client/blob/85a6b994185edbe14 …
> Fix AI AdjustSettings to create correct tools

- libs/s25main/Loader.cpp
- tests/s25Main/benchmarks/CMakeLists.txt
Fixes #1420
Instead of renaming our new files to UPPERCASE I created code to detect the lower case filenames which IMO is nicer as e.g. our resource IDs are lowercase and most other resources are too.
Factored out into a new function for clarity
> Custom nations are lowercase -> Fix loading code

- CMakeLists.txt
- README.md
- libs/rttrConfig/CMakeLists.txt
- libs/rttrConfig/build_version_defines.h.cmake
- libs/rttrConfig/src/RTTR_Version.cpp
- libs/rttrConfig/src/RTTR_Version.h
- libs/s25client/s25client.cpp
- libs/s25main/Debug.cpp
- libs/s25main/SavedFile.cpp
- libs/s25main/Settings.cpp
- libs/s25main/desktops/dskLAN.cpp
- libs/s25main/desktops/dskLobby.cpp
- libs/s25main/desktops/dskMenuBase.cpp
- libs/s25main/drivers/VideoDriverWrapper.cpp
- libs/s25main/ingameWindows/iwLobbyConnect.cpp
- libs/s25main/ingameWindows/iwOptionsWindow.cpp
- libs/s25main/network/GameClient.cpp
- libs/s25main/network/GameServer.cpp
- tests/rttrConfig/testRttrConfig.cpp
For stable the version is an actual version and does not contain the date, hence the need for a new constant
Using `constexpr const char*` now instead of defines
> Introduce separate constant for build date 

- libs/s25main/convertSounds.cpp
Fix build with Boost 1.77 (missing <algorithm> include)
Needed for std::transform which is defined within <algorithm>. The
build fails with newer versions	of Boost, presumably because of
a missing indirect include.
Closes: https://bugs.gentoo.org/808767
> Fix build with Boost 1.77 (missing <algorithm> include)

- libs/libsamplerate/include/samplerate.hpp
Since libsndfile/libsamplerate@26d92c369394bcd0b0cea488890edce1a0d757d5, initialising libsamplerate with 0 channels or less causes a SIGABRT.
> Fix test broken by change in libsamplerate 0.2.0

- libs/s25main/Savegame.cpp
- libs/s25main/buildings/nobMilitary.cpp
- libs/s25main/desktops/dskGameInterface.cpp
- libs/s25main/desktops/dskGameInterface.h
- libs/s25main/resources/ArchiveLocator.cpp
- libs/s25main/resources/ResourceId.cpp
When a Military building is captured and recaptured before all capturers arrived they are told about that but not removed from the list in the building leading to dangling pointers
Fixes #1452
Also fixes some output issues mentioned in the forum post on this bug report.
> Fix corrupted data on attack

- libs/s25main/WindowManager.cpp
- libs/s25main/WindowManager.h
- libs/s25main/desktops/dskGameInterface.cpp
- libs/s25main/desktops/dskLobby.cpp
- libs/s25main/ingameWindows/iwAction.cpp
- libs/s25main/ingameWindows/iwAction.h
- tests/s25Main/UI/testFont.cpp
- tests/s25Main/UI/testVideoDriver.cpp
- tests/s25Main/UI/testWindowManager.cpp
- tests/s25Main/UI/uiHelper/uiHelper/uiHelpers.cpp
- tests/s25Main/UI/uiHelper/uiHelper/uiHelpers.hpp
- tests/s25Main/lua/testLuaGUI.cpp
When pressing ESC the window was directly deleted instead of first calling Close which triggers a settings update for e.g. the tools window.
Refactor this so deleting a window is purely done by the WindowManager and before deleting Close is always called.
Add tests which catch this.
Also some changes to tests to avoid log spam and fix possibly missed mock-verify calls.
Fixes #1455
> Fix saving of settings when pressing ESC

- libs/s25main/addons/AddonEconomyModeGameLength.h
this fixes a bug introduced with commit https://github.com/Return-To-The-Roots/s25client/commit/7140756b88567f6bb0ab406274818135affa169a
where economy mode game length didn't match the selected length any more, because in the for loop instead of starting at index 1 as before iteration started at index 0.
> bugfix regarding economy mode game length

- data/RTTR/texte/de/keyboardlayout.txt
- data/RTTR/texte/de/readme.txt
- data/RTTR/texte/keyboardlayout.txt
- data/RTTR/texte/readme.txt
- extras/videoDrivers/SDL2/VideoSDL2.cpp
- libs/common/include/Rect.h
- libs/common/include/RectOutput.h
- libs/rttrConfig/src/RttrConfig.cpp
- libs/rttrConfig/src/files.h
- libs/s25client/s25client.cpp
- libs/s25main/controls/ctrlText.cpp
- libs/s25main/controls/ctrlText.h
- libs/s25main/ingameWindows/iwSave.cpp
- libs/s25main/ogl/glFont.cpp
- libs/s25main/ogl/glFont.h
- tests/s25Main/UI/testControls.cpp
- Remove version and year from header avoiding the need to update them
- Add release notes for 0.9.x
- Update copyright year to 2022
- Show user data folder in the console window and the savegame folder in the load game window:
Additionally I removed the redundant `RTTR_CONFIG` (same as `RTTR_USERDATA`) and added an option to the text-control to have a max-length to avoid overlong user names etc. from breaking the window. Not really great yet, but does its job.
> Update Ingame-Readmes and display user-data folder

- .github/workflows/release.yml
See https://trstringer.com/github-actions-multiline-strings/ for the multiline string workaround.
Test:
```
$ tagName=v0.9.0
$ tagType=$(git cat-file -t $tagName)
$ if [[ "$tagType" == "tag" ]]; then echo "Ok"; fi
Ok
$ tagMsg="$(git tag -l --format='%(contents)' $tagName)"
$          echo "TAG_MSG<<EOF" >> $GITHUB_ENV
$          echo "$tagMsg" >> $GITHUB_ENV
$          echo "" >> $GITHUB_ENV
$          echo "EOF" >> $GITHUB_ENV
$ cat $GITHUB_ENV
TAG_MSG<<EOF
- bugfixes
- better performance
- improved networking code
- LUA script support
- updated to SDL2
- included map editor
- builtin random map generator
EOF
```
Closes #1427
This should work. Of course we can only see that in the next release
> Include tag annotation in releases

- libs/s25main/TerrainRenderer.cpp
- libs/s25main/TerrainRenderer.h
- libs/s25main/desktops/dskGameInterface.cpp
- libs/s25main/ingameWindows/iwObservate.cpp
- libs/s25main/world/GameWorldView.cpp
- libs/s25main/world/GameWorldView.h
- libs/s25main/world/GameWorldViewer.cpp
- libs/s25main/world/GameWorldViewer.h
- tests/s25Main/UI/testControls.cpp
- tests/s25Main/integration/testGameWorldView.cpp
Move maxNodeAltitude from TerrainRenderer to GameWorldViewer
This field was initialized to late: In GenerateOpenGL
It is used by the GameWorldView constructor: Through the `Move` function which recalculates the first and last map points to draw based on the max height.
This moves makes the value available very early.
Also adds tests and a little refactoring of the `MoveTo` function (move the relative move into new `MoveBy`)
Fixes #1456
> Fix drawing glitch on start

- libs/common/include/helpers/mathFuncs.h
- libs/s25main/BuildingRegister.cpp
- libs/s25main/GameInterface.h
- libs/s25main/buildings/nobUsual.cpp
- libs/s25main/buildings/nobUsual.h
- libs/s25main/desktops/dskGameInterface.cpp
- libs/s25main/desktops/dskGameInterface.h
- libs/s25main/gameData/BuildingConsts.h
- libs/s25main/ingameWindows/iwAction.cpp
- libs/s25main/ingameWindows/iwBuildingProductivities.cpp
- libs/s25main/ingameWindows/iwBuildingProductivities.h
- libs/s25main/ingameWindows/iwRoadWindow.cpp
- libs/s25main/ingameWindows/iwRoadWindow.h
- tests/s25Main/UI/testIngameWindow.cpp
- tests/s25Main/integration/testDskGameInterface.cpp
- tests/s25Main/integration/testGamePlayer.cpp
- tests/s25Main/simple/testGameData.cpp
- tests/s25Main/simple/testGameTypes.cpp
Some refactoring related to the productivity handling, added tests to reproduce the issue and ensure related things (e.g. that buildings producing something are "Usual" buildings)
Also reorder the buildings according to the original with 4 buildings added:
- Forester below woodcutter
- Iron smelter below armoury
- Donkey-breeder below pig farm
- Charburner below mines
Fixes #1454
Result (old RttR, S2, new RttR): 
CC @Spikeone
> Fix missing forester productivity

- data/RTTR/MUSIC/S2_Standard.pll
- libs/s25main/Playlist.cpp
- libs/s25main/Playlist.h
- libs/s25main/ingameWindows/iwMusicPlayer.cpp
- libs/s25main/ingameWindows/iwMusicPlayer.h
- tests/s25Main/audio/testPlaylist.cpp
The repeats now actually mean repeats, i.e. a value of 1 repeats the song once, playing it twice.
On ordered playlists this will play each song N+1 times before starting the next.
For random playlists it doesn't matter much, but a higher value basically increases the chance of playing the same song again, up to N+1 times (in total).
After all songs of the playlist have been player N+1 times the whole playlist is reshuffled (if set) and restarted.
Fixes #1480
Basically uses "Option 5" which should please everyone.
> Fix meaning of playlist repeats and make playlists infinite

- libs/s25main/controls/ctrlEdit.cpp
- libs/s25main/desktops/dskLobby.cpp
- libs/s25main/desktops/dskLobby.h
- libs/s25main/ingameWindows/iwDirectIPConnect.cpp
- libs/s25main/ingameWindows/iwDirectIPConnect.h
- tests/s25Main/UI/testDskGameLobby.cpp
- tests/s25Main/UI/testIngameWindow.cpp
- tests/s25Main/integration/testGameWorldView.cpp
This solves 2 issues:
- Being unable to connect to games with the tagged (stable) versions because the extraction of the server revision only works for the data-as-version format
- A crash when connecting with the nightly due to a C&P mistake which removed the password-edit from the connect dialog
Fixes #1492
Also a bit cleanup:
- Setting focus on one edit removes it from the others of the same parent
- Remove the SetHost/SetPort functions that were only used once (left-over from the refactoring the introduced the connect function)
> Fix connection issues

- .github/workflows/unit-tests.yml
- libs/common/include/Point.h
- libs/s25main/ai/aijh/AIPlayerJH.cpp
- tests/s25Main/benchmarks/CMakeLists.txt
As LLVM APT repos for clang-13 on Ubuntu 20.02 are now available we can test this on CI.
This requires fixing a more pedantic behavior: Giving a custom (even defaulted) copy ctor requires now also a custom copy assignment operator if that is wanted.
Another warning found an actual bug in the AI code, although the effect should be minor in practice.
See the individual commits for details.
Closes #1430
> Add support for Clang 13 and fix ordering of tools by AI

- libs/s25main/WindowManager.cpp
- libs/s25main/ingameWindows/IngameWindow.cpp
- libs/s25main/ingameWindows/IngameWindow.h
- libs/s25main/ingameWindows/TransmitSettingsIgwAdapter.cpp
- libs/s25main/ingameWindows/TransmitSettingsIgwAdapter.h
- libs/s25main/ingameWindows/iwAddons.cpp
- libs/s25main/ingameWindows/iwChat.cpp
- libs/s25main/ingameWindows/iwConnecting.cpp
- libs/s25main/ingameWindows/iwDirectIPCreate.cpp
- libs/s25main/ingameWindows/iwMissionStatement.cpp
- libs/s25main/ingameWindows/iwMsgbox.cpp
- libs/s25main/ingameWindows/iwObservate.cpp
- libs/s25main/ingameWindows/iwPleaseWait.cpp
- tests/s25Main/UI/testIngameWindow.cpp
- tests/s25Main/UI/testWindowManager.cpp
Additionally to regular close behavior (close on right click, ESC, ...) and full custom behavior we need a mode that only ignores right click, e.g. for the observation window.
Hence introduce an enum instead of the bool which additionally makes the window constructors much more readable.
Also a bit refactoring in the draw code: Translated comments, renamed snake_case variables and related functions for easier understanding of the code and this change. Additionally updated the turtle submodule which now uses less of the preprocessor
> Use a 3-state enum for the window close behavior

- shell.nix
The shell.nix file which was added to the project is a quite bit outdated and does not result in a runtime which is capable of compiling the game.
As i am currently running nixos (which is a distro build around the package manager nix, which at the end, the shell.nix can possibly be used in), i gave it a try to update it to the current state of the nix eco system.
The old version was mostly broken due to not having a SDL2 which includes a `libSDL2Main.a`, thus the cmake modules do not find the needed version information. 
edit:
sorry for force pushing again. but after cleaning old devShells i noticed that it also requires libsamplerate which was because of some reason on the shell before by something else.
> Update nix shell to current repository eco system.

- libs/s25main/Loader.cpp
- libs/s25main/addons/AddonCatapultGraphics.h
- libs/s25main/addons/AddonMilitaryAid.h
- libs/s25main/world/GameWorldView.cpp
- libs/s25main/world/GameWorldView.h
Fixes #1521 
Also brings back Military Aid to its full functionality (note the icon which indicates that enemy guardhouse can be attacked):
Submodule which needs to be merged prior to this one so that I can update submodule refs: https://github.com/Return-To-The-Roots/languages/pull/20
> Plugin fixes

- .github/workflows/static-analysis.yml
This allows to remove the ignore-files workaround and hopefully fixes the recent false-positives such as
> `doc/lua/constants.md:12:3 MD051/link-fragments Link fragments should be valid [Context: "[Wares / Goods](#Wares-/-Goods)"]`
> CI: Update markdown-lint action to 1.5

- libs/common/include/helpers/mathFuncs.h
- tests/common/testMathHelpers.cpp
> Add lerp and inverseLerp helper functions

- libs/s25main/figures/nofBuilder.cpp
- libs/s25main/figures/nofGeologist.cpp
Use better alternatives like `format` or `snprintf` to avoid warnings about using this deprecated, unsafe function.
Mainly affects the submodules so updated them all.
Closes #1546
> Remove use of sprintf

- libs/s25main/gameTypes/LanGameInfo.h
GCC 13 (as usual for new compiler releases) shuffles around some internal includes and so <cstdint> etc is no longer transitively included.
See https://www.gnu.org/software/gcc/gcc-13/porting_to.html.
Closes: https://github.com/Return-To-The-Roots/libsiedler2/issues/20
Bug: https://bugs.gentoo.org/891713
> LanGameInfo: Add missing <cstdint> include

- libs/s25main/Settings.cpp
- libs/s25main/Settings.h
- libs/s25main/desktops/dskGameInterface.cpp
- libs/s25main/desktops/dskOptions.cpp
- libs/s25main/ingameWindows/iwDirectIPCreate.cpp
- tests/s25Main/locale/testLocalization.cpp
The information about current GF, GF length, NWF length and ping are usually not relevant.
So add an option to enable them when required.
Also introduce an enum for the IDs in dskOptions to be able to add/change stuff.
Closes https://github.com/Return-To-The-Roots/s25client/issues/1549
> Add option to disable GF debug data

- extras/videoDrivers/SDL2/VideoSDL2.cpp
This should fix #1526 and #1500.
The SDL2 video driver got stuck on the logic regarding `mouseMoved`. I didn't see any reason why to catch the first mouse move only. The problem is, that the Msg_MouseMove is only sent on the first time -> no mouse pan working. So this PR removes the logic around `mouseMoved` and basically sends every mouse motion event.
> Fix mouse panning issues in SDL2 video driver

- libs/s25main/gameData/BuildingConsts.h
Iron **ore** should be displayed as shown here:
(S2gold)
Currently Iron is displayed 
(s25rttr_20230312)
> Fix miner produced icon from iron to iron ore

- libs/s25main/GameManager.cpp
- libs/s25main/Settings.cpp
- libs/s25main/Settings.h
- libs/s25main/desktops/Desktop.cpp
- libs/s25main/desktops/dskGameInterface.cpp
- libs/s25main/desktops/dskOptions.cpp
Fixes https://github.com/Return-To-The-Roots/s25client/issues/1566
Issue was when vsync is set to number above 0, it is read as bool -> 1 and that is used as FPS limit
> FIX issue-1566 - framerate stuck to 1

- cmake/Modules/GetGitRevisionDescription.cmake
- cmake/Modules/GetGitRevisionDescription.cmake.in
Update GetGitRevisionDescription CMake module from the author's git repository.
https://github.com/rpavlik/cmake-modules/blob/main/GetGitRevisionDescription.cmake
https://github.com/rpavlik/cmake-modules/blob/main/GetGitRevisionDescription.cmake.in (new file; now required by the former)
Without the update building from a git worktree (see `man git-worktree`) fails as follows:
```
CMake Error at CMakeLists.txt:59 (message):
Could not get git revision.  The source has to be in a git repo or you have
to define RTTR_REVISION
```
> Update GetGitRevisionDescription CMake module

- libs/s25main/ingameWindows/iwMilitaryBuilding.cpp
The military building window would draw parts of its UI outside the window when shaded (aka. minimized).
> Prevent drawing outside the window when shaded

- .github/workflows/unit-tests.yml
- appveyor.yml
- Boost on the GHA macos-12 image was updated to 1.82 as reported by @falbrechtskirchinger
- On Appveyor VS 2019 1.73 was replaced by 1.77
Closes #1595
> CI: Update Boost versions

- libs/s25main/WindowManager.cpp
- libs/s25main/WindowManager.h
- libs/s25main/controls/ctrlBaseTooltip.cpp
- libs/s25main/controls/ctrlBaseTooltip.h
When a tooltip is currently being shown and its text is changed, update the displayed text.
> Update text in shown tooltip

- libs/s25main/WindowManager.cpp
Tooltips are placed at a consistent distance and the cursor doesn't overlap.
Before:
(Excuse the screen tear. Didn't catch that when I took the screenshots.)
After:
> Fix cursor overlapping tooltips

- libs/common/include/Point.h
- libs/libGamedata/gameData/TerrainDesc.h
- libs/s25main/TerrainRenderer.cpp
- libs/s25main/TerrainRenderer.h
- libs/s25main/ogl/glSmartBitmap.cpp
- libs/s25main/ogl/glSmartBitmap.h
- libs/s25main/ogl/glTexturePackerNode.cpp
- libs/s25main/world/GameWorldView.cpp
- tests/libGameData/testGameData.cpp
- tests/s25Main/UI/testTexturePacker.cpp
Add a using alias `PointF = Point<float>`, remove a bunch of local aliases, and refactor uses of `Point<float>`. One use in `testPoint.cpp` is left unchanged for consistency within the test case.
Partly extracted from #1594 and expanded in scope.
To-do:
> Add using alias PointF = Point<float> and refactor

- libs/s25main/ingameWindows/IngameWindow.cpp
- libs/s25main/ingameWindows/IngameWindow.h
* Remove unused data members (`last_down`, `last_down2`).
* Refactor button handling for #1606.
* Fix incorrect texture used for the close button (pressed state).
~~I'll rebase #1606 and implement discussed changes before this is ready for consideration.~~
> Clean up and refactor IngameWindow button handling

- libs/s25main/Settings.cpp
- libs/s25main/Settings.h
- libs/s25main/ingameWindows/IngameWindow.cpp
- libs/s25main/ingameWindows/IngameWindow.h
- tests/s25Main/UI/testIngameWindow.cpp
* Remove unneeded `PersistentWindowSettings` constructors and move default initialization in class.
* Look up  `PersistentWindowSettings` only once in `IngameWindow` (assumes pointer stability). This will make more of a difference when more settings are saved in these PRs:
* #1601
* #1606
* Save and restore the minimized state of in-game windows. This required some more changes to avoid calling unqualified virtual `Resize()` from the constructor.
> Refactor PersistentWindowSettings and persist window minimized state

- libs/s25main/ingameWindows/iwObservate.cpp
- libs/s25main/ingameWindows/iwObservate.h
- libs/s25main/world/GameWorldView.cpp
- libs/s25main/world/GameWorldView.h
Synchronize visibility of game world view HUD elements from parent to child views (like the observation window).
@Spikeone identified this bug in #1604 [here](https://github.com/Return-To-The-Roots/s25client/pull/1604#issuecomment-1638412706).
> Synchronize game world view HUD visibility settings

- libs/s25main/ingameWindows/IngameWindow.cpp
- libs/s25main/ingameWindows/IngameWindow.h
- libs/s25main/ingameWindows/iwBuildings.cpp
- libs/s25main/ingameWindows/iwDistribution.cpp
- libs/s25main/ingameWindows/iwWares.cpp
As mentioned, I've discovered a bug introduced in 938f355891d #1609. This is a very quick fix. Let me know if you'd prefer to store the full size in `IngameWindow` and add a `GetFullSize()` member function, or maybe a different solution entirely.
Commit message follows:
<hr>
Some windows position their buttons based on GetSize().y, which results in incorrect placement if the window is persisted and minimized. Replace uses of GetSize().y with the full window height.
Affected windows:
* iwBuildings
* iwDistribution
* iwWares
> Fix button placement in minimized in-game windows

- libs/s25main/desktops/dskOptions.cpp
Extracted from #1553
I needed some more space and a way to ease adding a new option.
New:
> Refactor options screen

- libs/s25main/Settings.cpp
- libs/s25main/Settings.h
- libs/s25main/SnapOffset.h
- libs/s25main/WindowManager.cpp
- libs/s25main/WindowManager.h
- libs/s25main/ingameWindows/IngameWindow.cpp
- libs/s25main/ingameWindows/IngameWindow.h
- tests/s25Main/UI/testIngameWindow.cpp
- tests/s25Main/UI/testWindowManager.cpp
Make windows align along edges within a certain snap distance.
Fixes #574
To-do:
> Implement window snapping

- doc/lua/events.md
- libs/s25main/desktops/dskGameLobby.cpp
- libs/s25main/lua/LuaInterfaceGameBase.cpp
- libs/s25main/lua/LuaInterfaceSettings.cpp
- libs/s25main/lua/LuaInterfaceSettings.h
- tests/s25Main/lua/testLuaSettings.cpp
- tests/testData/maps/LuaFunctions.lua
We need lua functionality to have possibility to disable the map preview for missions. So the user can not see the map in advance.
> Add new function to enable/disable preview of map to lua

- libs/s25main/ingameWindows/iwStatistics.cpp
- libs/s25main/ingameWindows/iwStatistics.h
Add info to statistic window to see if player is defeated. Add info for computer player or human player.  Like in the original settler 2. So it is obvious to see which players are already defeated.
> Add player info (Number for human player, COMP for ai and change to defeated if player is defeated)

- .github/workflows/unit-tests.yml
The brew installed boost changed to a new version. Update the code to just always use the latest in that folder instead of a specific one.
> CI: Fix finding Boost on OSX

- libs/s25main/ingameWindows/iwStatistics.cpp
- libs/s25main/ingameWindows/iwStatistics.h
> Show alliances in statistic view

- libs/s25main/lua/LuaWorld.cpp
The recalculation around big static objects did not work properly.
Before this patch:
After this patch:
Maybe cause of #1516 and #1520
> Fix recalculating BQ around big static objects

- libs/s25main/ingameWindows/iwAIDebug.cpp
Hello!
According to the code in the OnDraw method
`else if(overlay < 13)
font.Draw(curPos, helpers::toString(ai->GetResMapValue(pt, AIResource(overlay - 4))), FontStyle{},
COLOR_YELLOW);`
order of overlay tabs should be the same as AIResource enum order. In actual code branch, for example, "Wood" tab shows info about gold mine deposits.
> Overlay tabs in AI Debug Window are not displaying relevant information

- libs/s25main/MusicPlayer.cpp
- tests/s25Main/audio/testSounds.cpp
When playing a song from the playlist `Play(1)` is called which means "1 repeat" not "play once".
This leads to #1480 which was reported on Discord to still happen. Fix is to remove the argument to default to *playing* only once.
Also add a test although it is actually a logic confusion.
> Don't repeat all songs from playlist once

- libs/libGamedata/gameData/SelectionMapInputData.h
- libs/s25main/Window.cpp
- libs/s25main/Window.h
- libs/s25main/controls/controls.h
- libs/s25main/controls/ctrlMapSelection.cpp
- libs/s25main/controls/ctrlMapSelection.h
- tests/s25Main/UI/testMapSelection.cpp
Add map selection control for campaigns
> Add map selection control for campaigns including test

- libs/libGamedata/lua/CampaignDataLoader.h
- libs/s25main/GamePlayer.cpp
- tests/common/testContainerUtils.cpp
- tests/common/testMultiArray.cpp
- tests/common/testRect.cpp
- tests/libGameData/testGameData.cpp
- tests/s25Main/UI/testMapSelection.cpp
- tests/s25Main/audio/testSounds.cpp
- tests/s25Main/campaign/testCampaignLuaFile.cpp
- tests/s25Main/integration/testAI.cpp
- tests/s25Main/integration/testBaseWarehouse.cpp
- tests/s25Main/integration/testPacts.cpp
- tests/testHelpers/rttr/test/TmpFolder.hpp
This is my first pull request. Please have mercy :D
GamePlayer::SuggestPact will not allow a request when pact.accepted = true
If you have a pact with a duration that has expired, accepted will never be reset. Just the duration will be set to 0.
I figured this would be the simplest way.
Please let me know if you need more stuff like testing. I am not familiar with that, so I would need more help on that.
A simple test map if it helps...
[testpact.zip](https://github.com/Return-To-The-Roots/s25client/files/10984927/testpact.zip) The AI sends a pact request and (if you accept) will send a new request as soon the previous pact expired.
> Allow to offer a new pact after a pact duration has expired

- libs/s25main/buildings/noBuildingSite.cpp
- libs/s25main/buildings/nobHarborBuilding.cpp
- libs/s25main/ingameWindows/iwShip.cpp
- libs/s25main/ingameWindows/iwTransport.cpp
- libs/s25main/nodeObjs/noFlag.cpp
Use GetWareTex and GetWareTexStack texture interface instead of GetMapTexture.
- Adding new textures for additional wares is much easier because we have only one place to add a lookup for the new texture. Otherwise we have to add the code at each calling place. This is needed for the new wine addon (#1669) to add the new goods wine and grapes.
> Consistently use GetWareTex  and GetWareTexStack instead of GetMapTexture

- libs/s25main/figures/nofFarmhand.cpp
- libs/s25main/figures/nofFisher.cpp
- libs/s25main/ogl/glFont.cpp
- libs/s25main/world/World.cpp
- tests/s25Main/integration/testGameWorldView.cpp
The code triggers an assertion when 2 fishers try to get the last fish
from the same spot because only the first can get it.
So remove the fish when starting to fish such that it is already
unavailable when the 2nd starts fishing.
Fixes https://github.com/Return-To-The-Roots/s25client/issues/1674
Also a fix for some tests crashing depending on the order they are executed. (TextControlWorks & TableSorting due to glFont, the other due to the guiScale change)
> Fix fisher not getting the fish he caught

- libs/common/include/helpers/EnumRange.h
- tests/common/testEnumRange.cpp
The range iterator is a forward iterator, so add the necessary typedefs
See https://github.com/Return-To-The-Roots/s25client/pull/1657#discussion_r1594456973
> Make EnumRange iterators usable as iterators in std algorithms

- tools/release/bin/rttr.sh.cmake
Fixes https://github.com/Return-To-The-Roots/s25client/issues/1697
Reason was an inverted condition because the decision of downloading to file or memory was done in 2 places that needed to be kept in sync. Using a RAII wrapper for cURL makes it easier to merge those such that a single condition handles the distinction. It also makes the code cleaner.
> Fix updater

- libs/s25main/desktops/dskGameLobby.cpp
In one instance a NULL-check for the `lua` pointer was missing as the call should have been through a function.
Fixes #1701
> Fix crash when opening map settings

- libs/s25main/desktops/dskOptions.cpp
The inverted cursor setting never was applied when activating in settings. Just when activating ingame in advanced options. 
Just a very small fix.
> Fix inverted cursor is not saved in global settings

- libs/s25main/ingameWindows/iwSave.cpp
- libs/s25main/ingameWindows/iwSave.h
There is an off-by-one error when selecting the auto save interval:
- Entry 0 is "disabled"
- Entry 1 corresponds to index 0 in the interval array
- Hence the maximum valid value is size()
The code checked for >= size() and applied the "every GF" setting that
is the last entry.
Fix is to simply use `> size()` as the check.
Fixes https://github.com/Return-To-The-Roots/s25client/issues/1713
The new layout of the save window after the refactoring looks like this:
> Fix autosave interval setting

- .github/workflows/unit-tests.yml
The `macos-12` runner image is now removed. `macos-15` is available as preview, `macos-latest` is still at 14, so use that.
Also update the "latest GCC &Clang" compilers to the currently latest versions
> Fix & Update Github Actions CI

- libs/s25main/CheatCommandTracker.cpp
- libs/s25main/Cheats.cpp
- libs/s25main/Cheats.h
- libs/s25main/GameInterface.h
- libs/s25main/desktops/dskGameInterface.h
- libs/s25main/world/GameWorldBase.h
- libs/s25main/world/GameWorldViewer.cpp
- tests/s25Main/integration/testCheatCommandTracker.cpp
- tests/s25Main/integration/testCheats.cpp
Part of https://github.com/Return-To-The-Roots/s25client/pull/1679
> Add classic cheat to reveal map (F7)

- extras/videoDrivers/SDL2/CMakeLists.txt
- extras/videoDrivers/SDL2/VideoSDL2.cpp
Disable High DPI support/request for now until the GUI scaling is adjusted to support it.
See https://github.com/Return-To-The-Roots/s25client/issues/1621
Also require SDL2 2.0.5+ as even the EoL Ubuntu 18.04 (bionic) provides 2.0.8 so we can remove our checks/workarounds.
> Workaround GUI scaling issues with HighDPI enabled.

- libs/s25main/world/GameWorld.cpp
- tests/s25Main/integration/testTerritoryRegion.cpp
With the addon enabled the territory for the HQ won't be calculated correctly when they are too close.
The code runs into this condtion that reset the owner for territory gained by a newly placed HQ:
`ownerOfTriggerBld == oldOwner && oldOwner > 0 && reason == TerritoryChangeReason::Build` When the HQs are too close the position of the newly placed HQ already belongs to a player and as ownership wasn't yet set for the position of the HQ `ownerOfTriggerBld` wrongly refers to that player.
Fix by explicitely handling the case of "building" an HQ by setting `ownerOfTriggerBld` to the new owner of the point, which is the owner of the HQ.
Fixes #1733
> Fix improved alliances for close start positions

- libs/s25main/Loader.cpp
- libs/s25main/ingameWindows/IngameWindow.cpp
- libs/s25main/ingameWindows/IngameWindow.h
- libs/s25main/ingameWindows/iwEconomicProgress.cpp
- libs/s25main/ingameWindows/iwEconomicProgress.h
- libs/s25main/ingameWindows/iwMerchandiseStatistics.cpp
- libs/s25main/ingameWindows/iwMerchandiseStatistics.h
- libs/s25main/ingameWindows/iwMilitaryBuilding.cpp
- libs/s25main/ingameWindows/iwMilitaryBuilding.h
- libs/s25main/ingameWindows/iwObservate.cpp
- libs/s25main/ingameWindows/iwObservate.h
- libs/s25main/ingameWindows/iwShip.cpp
- libs/s25main/ingameWindows/iwShip.h
- libs/s25main/ingameWindows/iwStatistics.cpp
- libs/s25main/ingameWindows/iwStatistics.h
- tests/s25Main/UI/testWindowManager.cpp
Fixes https://github.com/Return-To-The-Roots/s25client/issues/1742
To avoid this whole class of issues introduce `IngameWindow::DrawContent` to allow  subclasses to handle only drawing its own content not also
checking whether they actually should or the window is minimized.
Also move the logic out of iwObservate::Draw to a timer. No need to update every frame, every second is enough.
> Don't draw content of ship window if minimized 

- libs/s25main/ingameWindows/iwSettings.cpp
Make the checkboxes cover the full width so that the texts don't get truncated. Also use constants for size and positions
Fixes #1746
> Adjust size of checkboxes in settings window

- Jenkinsfile
- tests/s25Main/integration/testCheats.cpp
- tools/ci/jenkins/build.sh
The test creates a desktop instance that requires access to the VideoDriver and potentially resources (graphics) which are not available at this point. This leads to failures when the test is not started after a test installing a test-videodriver in the same process.
Manually create the required instances without that desktop.
> Fix testCheats when running standalone

- .github/workflows/static-analysis.yml
- .github/workflows/unit-tests.yml
- CMakeLists.txt
- GHA drops Ubuntu 20 so upgrade to 22
- CMake 4 drops CMake 3.5, deprecates 3.10 so use 3.16 as the new minimum which is old enough to be easily available
- Update the submodules with mostly the same changes
The Windows CI failure will be fixed by #1759, see detailed description there and [this run](https://github.com/Return-To-The-Roots/s25client/commit/31a8eb41a78a9d2afa1b73e8312b13cb6a946855) with both combined.
It needs adjusting the required checks after OS upgrade.
- `Linux (gcc-9, ubuntu-20.04, Debug, 3.16.3, 1.71.0)` -> `Linux (gcc-9, ubuntu-22.04, Debug, 3.16.3, 1.73.0)`
- `Linux (gcc-10, ubuntu-20.04, Debug, true)` -> `Linux (gcc-10, ubuntu-22.04, Debug, true)`
> Fix/Avoid CI failures

- tests/s25Main/network/testGameClient.cpp
The tests verify the expected flow of events/state machine in the client
during a connect-map-download cycle.
If the map exists the flow is different as the map is reused and not
requested again.
Use a new folder for each test to avoid this.
Also add a test for the caching behavior observed "by accident".
Requires:
> Fix random failures in network tests 

- libs/common/include/Point.h
- libs/common/include/Rect.h
- libs/common/include/helpers/EnumRange.h
- libs/common/include/helpers/MaxEnumValue.h
- libs/common/include/helpers/OptionalEnum.h
- libs/common/include/helpers/Range.h
- libs/common/include/helpers/containerUtils.h
- libs/common/include/helpers/make_array.h
- libs/common/include/helpers/mathFuncs.h
- libs/common/include/helpers/random.h
- libs/common/include/helpers/serializeContainers.h
- libs/common/include/helpers/serializeEnums.h
- libs/common/include/helpers/toString.h
- libs/libsamplerate/include/samplerate.hpp
- libs/s25main/GameCommands.cpp
- libs/s25main/SerializedGameData.h
- libs/s25main/desktops/dskBenchmark.cpp
- libs/s25main/gameTypes/SettingsTypes.h
- libs/s25main/ingameWindows/iwTransport.h
- libs/s25main/mapGenerator/RandomUtility.h
- libs/s25main/ogl/FontStyle.h
- libs/s25main/random/DefaultLCG.h
- libs/s25main/random/XorShift.h
- libs/s25main/world/MapBase.h
- tests/common/testMathHelpers.cpp
- tests/common/testPoint.cpp
- tests/libsamplerate_cpp/testSamplerate.cpp
- tests/s25Main/integration/testFrontierDistance.cpp
This is shorter and easier to read and otherwise flagged by clang-tidy as `modernize-type-traits`
> Use C++17 variable templates for traits

- libs/libGamedata/lua/GameDataLoader.cpp
- libs/libGamedata/lua/GameDataLoader.h
- tests/libGameData/testGameData.cpp
One Windows CI was failing with a strange error that I cannot reproduce locally.
After a lot investigation I conclude that it is an optimization issue. Example:
```
main: include(foo)
foo: include(bar)
bar: error out
foo stores error from including bar
main stores (no) error from including foo
```
The error storing happens as `anyError |= !load(...)`. During optimization I assume it loads `anyError` before calling `load` which down the chain sets `anyError` to true but because `main` does not get an error from `foo` and preloaded the "false" we store false again overwriting the `true`.
But actually the error should propagate upwards: When main includes foo which includes bar and that aborts, then foo should also abort and not continue and same for main.
So the fix here is to throw an …
> Fix failure to detect failures when loading (Lua) game data

- libs/s25main/ingameWindows/iwSettings.cpp
The rowWidth constant use was missing the adjustment for the left offset. The window height also needs to be adjusted.
Before: Last control y = 124+26=150, height=172 (i.e. +22)
Now   : Last control y = 177 -> +22 = height
Fixes #1749 
Requires:
> Fix size of Settings window

- libs/common/include/Point.h
MSVC started to short-circuit the conjunction without using the new template parameter leading to instantiating `std::enable_if_t<false, int>` which fails with
> Failed to specialize alias template
Use `std::conjunction` to delay the evaluation
> Workaround MSVC issue with `Point` constructor

- tools/release/bundleWinFiles.sh.cmake
Updates libutil submodule with https://github.com/Return-To-The-Roots/libutil/pull/26/
I guess this needs further updating after libutil is merged so that it points to proper commit hash
> libutil: use GetUserNameExW to query user name on windows

- libs/s25main/desktops/dskOptions.cpp
Fixes #1779 
Sorry for that, I completely forgot about fixing that one thing.
Some "Common" settings had inconsistently big spacing between sections, I've unified this to smallest one and it made room for GameFrame info controls.
The audio/graphics used different spacing and they keep it for each row, so I've made them a separate constant.
With 100% scaling on 800x600:
With 200% scaling on 4k (on 100% it's fine too):
> Replace magic numbers with constants, unify spacing

- libs/s25main/ingameWindows/iwStatistics.cpp
The statistics for the eight player can not be hidden by clicking the portrait of the player in the statistics window. This works for all other players
> Allow to disable statistics for eight player

- extras/videoDrivers/SDL2/VideoSDL2.cpp
When RTTR failes to find the game files a SDL message box is created to ask the user to install the files.
But when passing a valid SDL_window to the message box, SDL tries to use tools like zenity or kdialog.
This libraries are not always installed on every linux distribution and the program just crashes.
Using nullptr instead of a window object makes SDL use an x11 backend to display the message box.
This should work for every x11 or wayland system.
At least it works for me (wayland)
Fixes https://github.com/Return-To-The-Roots/s25client/issues/1788
> Fixed crash on linux

- .github/workflows/unit-tests.yml
- extras/videoDrivers/SDL2/VideoSDL2.cpp
- libs/s25main/Window.cpp
- libs/s25main/Window.h
- libs/s25main/WindowManager.h
- libs/s25main/controls/ctrlBaseTooltip.h
- libs/s25main/controls/ctrlButton.cpp
- libs/s25main/controls/ctrlButton.h
- libs/s25main/controls/ctrlCheck.cpp
- libs/s25main/controls/ctrlCheck.h
- libs/s25main/controls/ctrlImage.cpp
- libs/s25main/controls/ctrlImage.h
- libs/s25main/controls/ctrlMapSelection.cpp
- libs/s25main/controls/ctrlMapSelection.h
- libs/s25main/desktops/dskMainMenu.cpp
- libs/s25main/ingameWindows/iwSettings.cpp
- tests/s25Main/UI/testControls.cpp
Avoid reporting duplicate mouse move events in SDL2
When warping the mouse a new event will be recorded with the SDL2
backend which might lead to handling that event multiple times.
For the right-click scrolling this leads to a potential infinite loop of
zero-sized movements.
Added an option to change the smart cursor setting in the ingame option window to test it which requires a tooltip for the checkbox due to the limited width.   
- Added support for that
- moved duplicated function used by that to `Window` class
- support chaining for some options to use a build-like pattern
> Fix lags in right-click scrolling for SDL2

- libs/common/include/helpers/win32_nanosleep.h
- libs/common/src/helpers/win32_nanosleep.cpp
fix compilation under msys2 mingw
> mingw compat
