INSTALL, README.md
Fixes some typos and tries to make working with submodules work for the uninitiated
=> Update INSTALL and README

cmake/Modules/FindMiniupnpc.cmake
This fixes issue #167 (needs another change to libutil, also incoming!)
=> Add FindMiniupnpc module for cmake

build/postinstall.sh.cmake, build/preinstall.sh.cmake
pretty mechanical, github doesn't show the diff nicely, though :(
=> Add FreeBSD support to pre/postinstall

src/controls/ctrlChat.cpp, src/ingameWindows/iwDiplomacy.cpp, src/ingameWindows/iwMinimap.cpp, src/ingameWindows/iwSettings.cpp, src/ingameWindows/iwSettings.h, src/ingameWindows/iwShip.cpp, src/ingameWindows/iwShip.h
Also squelch the annoying virtual overload warnings
=> Clean up some warnings about unused fields and constants

src/GlobalGameSettings.cpp, src/addons/AddonMilitaryHitpoints.h, src/addons/const_addons.h, src/figures/nofSoldier.cpp, src/figures/nofSoldier.h, src/ingameWindows/iwMilitaryBuilding.cpp
Added a new addon. The hitpoints will be shown above the soldier picture.
It's my first pull request. I have no idea, if i have done it right. If not, please tell me the right way. Maybe I had to create a branch first...
=> Added Addon to see hitpoints in military buildings

src/ingameWindows/iwMilitaryBuilding.cpp
Removed max hitpoints. Colour of hitpoints will be red if a soldier has not the maximal amount of hitpoints.
=> Improved hitpoint text

src/GameWorld.cpp, src/GameWorldBase.cpp, src/GameWorldBase.h, src/GameWorldGame.cpp, src/GameWorldGame.h, src/RoadSegment.cpp, src/figures/noFigure.cpp, src/gameTypes/HarborPos.h, src/gameTypes/MapNode.cpp, src/gameTypes/MapNode.h
- Move MapNode Serialization to its file
- Iterator usages
- Whitepaces
=> Some refactoring

src/GameWorld.cpp, src/GameWorld.h, src/GameWorldGame.cpp, src/ai/AIPlayerJH.cpp
- Don't throw error if lua file does not exist
- Correctly set the BQ (Adresses #312)
- Factor out methods
- Show unknown object in debug builds
=> Refactor game loading

src/CatapultStone.cpp, src/GameClient.cpp, src/GameWorldGame.cpp, src/GameWorldGame.h, src/TerritoryRegion.cpp, src/buildings/noBaseBuilding.cpp, src/buildings/noBaseBuilding.h, src/figures/noFigure.cpp, src/figures/noFigure.h, src/figures/nofActiveSoldier.cpp, src/figures/nofBuildingWorker.cpp, src/figures/nofBuildingWorker.h, src/figures/nofCarrier.cpp, src/figures/nofCatapultMan.cpp, src/figures/nofFarmhand.cpp, src/figures/nofGeologist.cpp, src/figures/nofGeologist.h, src/figures/nofTradeDonkey.cpp, src/nodeObjs/noAnimal.cpp, src/nodeObjs/noMovable.cpp, src/nodeObjs/noMovable.h, src/nodeObjs/noShip.cpp
This revisits most of the functions where one has to go over a border of the map. Especially wandering of figures over borders was not supported. The rest is mainly refactoring and small fixes to make things better/clearer/faster
=> Better support for endless map

src/GameClient.cpp, src/figures/nofGeologist.cpp, src/gameTypes/PactTypes.cpp, src/gameTypes/PactTypes.h, src/ingameWindows/iwAIDebug.h, src/ingameWindows/iwShip.cpp
This fixes some warnings during compilation.
It also fixes the `FormatGFTime` function that shows to many minutes for >=1h time
Merge after #461 ! (submodule conflict)
=> Warning fixes

release/bin/macos/rttr.command, src/drivers/DriverWrapper.cpp, src/drivers/DriverWrapper.h, src/main.cpp
This should help in debugging issues like #472 
It also shows the current directory when rttr is started (we use relative paths internally)
@Flow86 Please merge as soon as this completes building in travis to help that case
=> Add more info about failing drivers #472

src/GameClient.cpp, src/GameServer.cpp, src/nodeObjs/noFlag.cpp, src/test/testMap.cpp, src/world/BQCalculator.h
This currently does the following:
- S2 Map read/write produces no file change
- Altitude between S2 and RttR map matches
- BQs between S2 and RTTR matches (#82)
=> Add more testing for World loading and fix related bugs

src/test/WorldFixture.h, src/test/testMap.cpp, src/world/World.cpp
=> Fix wrong flag BQ at border region

src/BasePlayerInfo.cpp, src/BasePlayerInfo.h, src/JoinPlayerInfo.cpp, src/JoinPlayerInfo.h, src/lua/LuaInterfaceGame.cpp, src/lua/LuaPlayer.cpp, src/lua/LuaPlayerBase.cpp, tests/maps/LuaFunctions.lua
- Get player color
- save/load
- AIConstructionOrder
- Clean up script
=> Fix lua functions

src/GameObject.cpp, src/GameObject.h, src/WindowManager.cpp, src/drivers/VideoDriverWrapper.cpp, src/drivers/VideoDriverWrapper.h, src/ingameWindows/IngameWindow.cpp, src/ingameWindows/IngameWindow.h, src/ingameWindows/iwDemolishBuilding.cpp, src/ingameWindows/iwObservate.cpp, src/ingameWindows/iwObservate.h, src/world/GameWorldView.cpp, src/world/GameWorldView.h, src/world/World.h
- Also some minor things in functions touched by that
- Reorder GameObject members static/nonstatic
- INVALID_ID
- IsMinimized
- accept points
- Return points in radius with point included
=> Fix some inaccuracies in Observate follow feature

CMakeLists.txt, src/main.cpp, src/ogl/glArchivItem_Bitmap_Player.cpp
=> Fix crash if log folder does not exist

appveyor.yml, src/GameClient.cpp, src/gameTypes/FoWNode.h, src/gameTypes/MapNode.cpp, src/test/testRegressions.cpp, src/world/GameWorldGame.cpp, src/world/GameWorldGame.h
Fixes #538 
Bug was due to "prevent border stone blocking". If there is a use case for that, please report and add test case.
=> Fix missing borderstones and add test

src/FramesInfo.cpp, src/FramesInfo.h, src/GameClient.cpp, src/GameMessages.h, src/GameServer.cpp, src/GameServer.h, src/GlobalGameSettings.cpp, src/GlobalGameSettings.h, src/WindowManager.cpp, src/desktops/dskGameInterface.cpp, src/desktops/dskHostGame.cpp, src/gameData/MinimapConsts.h, src/ingameWindows/IngameWindow.cpp, src/ingameWindows/IngameWindow.h, src/ingameWindows/iwAction.cpp, src/ingameWindows/iwHelp.cpp, src/ingameWindows/iwMinimap.cpp, src/ingameWindows/iwMissionStatement.cpp, src/ingameWindows/iwMissionStatement.h, src/ingameWindows/iwObservate.cpp, src/lua/LuaInterfaceSettings.cpp, src/lua/LuaInterfaceSettings.h, src/lua/LuaPlayer.cpp, src/nodeObjs/noStaticObject.h, src/test/LuaSettingsTests.cpp, src/test/LuaTests.cpp
- Add ResetGameSettings (Closes #516)
- Fix static objects not blocking
- Fix Mission statement (Closes #521)
- Use `nil` as separator for restricted area
- Pause much faster
- Rightclick modal window fixed
=> Lua enhancement

CMakeLists.txt, build/postinstall.sh.cmake, build/preinstall.sh.cmake, build_paths.h.cmake, src/defines.h, src/files.h, src/main.cpp
=> Move files.h to main repo and fix some defines

src/pathfinding/PathConditions.h, src/test/testPaths.cpp, src/world/GameWorldBase.cpp
=> Fix human path near lava

src/ai/AIPlayerJH.cpp
=> AI should Block only for reachable warehouses

CMakeLists.txt, src/GameCommands.h, src/factories/GameCommandFactory.cpp, src/factories/GameCommandFactory.h
This seems to fix the bug (at least with the attached save game).
https://github.com/Return-To-The-Roots/s25client/issues/613
(don't know what the empty commit for 70b17db is still doing there)
=> Bugfix for issue 613

src/ingameWindows/iwSave.cpp
Fixes #618
Path names are already UTF8 so no need for any conversion
=> Don't try conversion from wstring to utf8 on save/load

src/ProgramInitHelpers.cpp, src/ProgramInitHelpers.h, src/QuickStartGame.cpp, src/Settings.cpp, src/WindowsCmdLine.cpp, src/WindowsCmdLine.h, src/main.cpp
Special chars caused conversion exception
Will also fix #616 by using `complete_path`
=> Fix crash on windows when starting from folder with special chars

src/CMakeLists.txt, src/desktops/dskSelectMap.cpp, src/ingameWindows/iwMapGenerator.cpp, src/mapGenerator/AreaDesc.cpp, src/mapGenerator/Map.cpp, src/mapGenerator/MapGenerator.cpp, src/mapGenerator/MapGenerator.h, src/mapGenerator/MapSettings.h, src/mapGenerator/MapStyle.h, src/mapGenerator/MapUtility.cpp, src/mapGenerator/MapUtility.h, src/mapGenerator/ObjectGenerator.cpp, src/mapGenerator/ObjectGenerator.h, src/mapGenerator/RandomConfig.cpp, src/mapGenerator/RandomConfig.h, src/mapGenerator/RandomMapGenerator.cpp, src/mapGenerator/RandomMapGenerator.h, src/mapGenerator/VertexUtility.cpp, src/random/XorShift.cpp, src/random/XorShift.h, src/test/AreaDescTest.cpp, src/test/CMakeLists.txt, src/test/MapTest.cpp, src/test/MapUtilityTest.cpp, src/test/ObjectGeneratorTest.cpp, src/test/RandomConfigTest.cpp, src/test/RandomMapGeneratorTest.cpp, src/test/VertexUtilityTest.cpp, src/test/main.cpp, src/test/testRandom.cpp
Fixes a few bugs in @vader1986 implementation and improves some things:
- Use seeded RNG for reproducible results
- Fix usage of fixtures in tests
- Make some static classes instances to store state
=> Use new random generator for random map generation

src/Debug.cpp, src/GameClient.cpp, src/GameClient.h, src/GameClientGF_Game.cpp, src/GameClientGF_Replay.cpp, src/GameMessage_GameCommand.cpp, src/GameMessage_GameCommand.h, src/GameMessages.h, src/GameServer.cpp, src/Random.cpp, src/Random.h, src/random/OldLCG.cpp, src/random/OldLCG.h, src/random/XorShift.h, src/test/testHelpers.cpp, src/test/testRandom.cpp
Templatizes Random class so the actual generator may be changed in the future.
Also add exhaustive tests for that.
=> Random rework

.travis.yml, appveyor.yml, src/GamePlayer.cpp, src/Pathfinding.cpp, src/RTTR_Assert.cpp, src/RTTR_Assert.h, src/SignalHandler.cpp, src/defines.h, src/figures/nofCarrier.cpp, src/macros.h, src/nodeObjs/noShip.cpp, src/nodeObjs/noShip.h, src/pathfinding/PathConditions.h, src/test/CreateSeaWorld.cpp, src/test/CreateSeaWorld.h, src/test/SeaWorldWithGCExecution.h, src/test/testSeaAttacking.cpp, src/test/testSeaWorldCreation.cpp, src/test/testSeafaring.cpp, src/world/GameWorldBase.cpp, src/world/GameWorldBase.h, src/world/MapLoader.cpp, src/world/World.cpp, src/world/World.h
This will fix #640.
The problem is that sea travels is only allowed over 400 movements. We should either mark harbors over that distance as unreachable in the first place or allow higher distances.
I'd opt for the second option. Opinions? @Flow86 @Spikeone
=> Sea faring over long distance fix

CMakeLists.txt, Jenkinsfile, build_paths.h.cmake, common/include/commonDefines.h, src/ProgramInitHelpers.cpp, src/ProgramInitHelpers.h, src/ingameWindows/iwLobbyRanking.cpp, src/ingameWindows/iwLobbyRanking.h, src/ingameWindows/iwLobbyServerInfo.h, src/s25client/s25client.cpp, src/test/s25Test.cpp, src/test/testSystem.cpp
- Allow absolute paths in config directories. Closes #692
- Skip building of updater (default when using absolute paths) with `RTTR_BUILD_UPDATER=OFF`
Note that the updater uses the paths found on the server which are defined on the build server. Hence any custom path will be ignored when running the updater especially as the updater will use the servers binary which obviously does not have the custom paths. The shell and batch script look for the updater and don't update if it isn't found so it won't be a problem if this is included even though the updater isn't. However they run the updater if it was found even when the cmake setting was turned off!
=> Make building for package systems easier

RTTR/sound.scs, appveyor.yml, common/include/helpers/converters.h, src/Loader.cpp, src/Loader.h, src/MusicPlayer.cpp, src/Window.h, src/ingameWindows/iwAddons.cpp, src/ingameWindows/iwDiplomacy.cpp, src/ingameWindows/iwDirectIPConnect.cpp, src/ingameWindows/iwDirectIPCreate.cpp, src/ingameWindows/iwLobbyConnect.cpp, src/ingameWindows/iwMusicPlayer.cpp, src/ingameWindows/iwSkipGFs.cpp, src/ingameWindows/iwTrade.cpp, src/test/helperFuncs.h, src/test/testLocalization.cpp, src/test/testLua.cpp
Fix addons not selectable in addons window if they are not visible on the first page
Fix locale dependent number conversions leading to not-loaded assets
=> Fix non-selectable addons and better locale support

src/GamePlayer.h, src/buildings/nobMilitary.cpp, src/buildings/nobMilitary.h, src/ingameWindows/iwMapDebug.cpp, src/lua/LuaInterfaceBase.cpp, src/lua/LuaInterfaceGame.cpp, src/lua/LuaInterfaceGame.h, src/lua/LuaInterfaceSettings.cpp, src/lua/LuaInterfaceSettings.h, src/lua/LuaPlayer.cpp, src/lua/LuaPlayer.h, src/test/testLua.cpp, src/test/testTerritoryRegion.cpp, src/world/TerritoryRegion.cpp, src/world/TerritoryRegion.h
=> Features and fixes

.travis.yml, Jenkinsfile, common/include/commonDefines.h, src/Debug.cpp, src/Loader.cpp, src/Loader.h, src/Minimap.cpp, src/addons/AddonExhaustibleWater.h, src/desktops/dskGameInterface.cpp, src/figures/nofGeologist.cpp, src/gameData/GuiConsts.h, src/gameData/TerrainData.cpp, src/gameData/TerrainData.h, src/ingameWindows/iwAddons.cpp, src/network/GameClient.cpp, src/network/GameServer.cpp, src/network/GameServer.h, src/ogl/glArchivItem_Bitmap.cpp, src/ogl/glArchivItem_Bitmap_Direct.cpp, src/ogl/glArchivItem_Bitmap_Player.cpp, src/ogl/glArchivItem_Font.cpp, src/random/XorShift.h, src/s25client/s25client.cpp, src/world/GameWorldGame.cpp, src/world/GameWorldView.cpp, src/world/World.cpp, src/world/World.h
Aims to have a nightly again and close some issues on the way
=> Further fixes

src/Game.cpp, src/Game.h, src/desktops/dskGameInterface.cpp, src/network/GameClient.cpp, src/network/GameClient.h
Fixes #783 
Also update submodules which do not use Boost.Locale (depends on big library ICU)
=> Fix lua intro message shown to early

src/world/GameWorldGame.cpp
Should fix #784, intention for  #758 was only to skip mineable mountains
=> Fill Meadow and buildable mountains with water

driver/include/driver/KeyEvent.h, driver/video/SDL/src/VideoSDL.cpp, driver/video/WinAPI/src/WinAPI.cpp, rttrConfig/files.h, src/GameManager.cpp, src/MusicPlayer.cpp, src/MusicPlayer.h, src/WindowManager.cpp, src/WindowManager.h, src/desktops/dskSplash.cpp, src/drivers/AudioDriverWrapper.cpp, src/drivers/VideoDriverWrapper.cpp, src/ingameWindows/iwMusicPlayer.cpp, src/ingameWindows/iwMusicPlayer.h, src/network/GameServerPlayer.cpp, src/s25client/s25client.cpp, src/test/helperFuncs.h, src/test/initTestHelpers.cpp, src/test/testLoader.cpp
Fix problems with music, cursor and screenshots
=> Fix usability issues

src/test/GameWithLuaAccess.h
See #824 as reference.
closes #824
=> Added missing override keyword in GameWithLuaAccess

src/libGamedata/CMakeLists.txt, src/s25Main.cmake
=> Fix lua include dir

src/desktops/dskCredits.cpp
=> Fix crash in credits

src/buildings/nobMilitary.cpp, src/ogl/glArchivItem_Sound_XMidi.cpp, src/test/testFrontierDistance.cpp, src/world/TerritoryRegion.cpp
A new built building was not handled symmetrically from either side.
This leads e.g. to a NEAR rating from one and a FAR rating from the other side
Fixes #871
=>  Fix different handling of new built military buildings 

src/Loader.cpp
On windows wrapping the command in quotes does not work
Fixes #875
=> Uses System::execute

cmake/warnings.cmake, src/lua/LuaTraits.h, src/test/GameWithLuaAccess.h, src/test/LuaBaseFixture.h, src/test/helperFuncs.h, src/test/testLua.cpp, src/world/GameWorldGame.cpp
Due to former refactoring the event was called multiple times and the 2nd with wrong values.
=> Add Tests for onOccupied and onExplored and fix EventOccupied call

src/QuickStartGame.cpp, src/Settings.cpp, src/Settings.h, src/controls/ctrlEdit.cpp, src/desktops/dskOptions.cpp, src/desktops/dskSinglePlayer.cpp, src/ingameWindows/iwDirectIPCreate.cpp, src/network/CreateServerInfo.h, src/network/GameServer.cpp
=> Make port for local games changeable

CMakeLists.txt, extras/CMakeLists.txt, extras/macosLauncher/CMakeLists.txt, tools/ci/jenkins/build.sh, tools/ci/travisBuild.sh, tools/release/CMakeLists.txt
Move all related stuff into tools/release
Update CI
Install libminiupnpc
Fixes #1014
=> Add RTTR_BUNDLE to control creating standalone bundles

libs/common/CMakeLists.txt, libs/common/include/Point.h, libs/common/include/PointOutput.h, libs/common/include/RTTR_Assert.h, libs/common/include/Rect.h, libs/common/include/commonDefines.h, libs/libGamedata/Rect.h, libs/rttrConfig/src/files.h, tests/common/CMakeLists.txt, tests/common/testPoint.cpp, tests/common/testRect.cpp, tests/s25Main/simple/testCollisionDetection.cpp, tests/testHelpers/rttr/test/random.cpp, tests/testHelpers/rttr/test/random.hpp
Pulls in the fix for destroyed textures and wrong BQ in the editor.
Also some tests created while refactoring Point/Rect (used by the editor)
=> Fix editor

external/CMakeLists.txt
=> external/CMakeLists: fix typo in comment

README.md
Sorry, my fork was completely messed up. The commits should be removed now and I updated the note in the README file.
=> Added a note for -G option for Mac OS X builds

.travis.yml, README.md, libs/libGamedata/lua/GameDataLoader.cpp, libs/rttrConfig/src/RttrConfig.cpp, tools/checkUTF8.sh, tools/ci/staticValidation.sh
Uses the weaker lexically_normal and adds script that check for usages of `::canonical(`
=> Don't use broken bfs::canonical on windows and enforce it

data/RTTR/texte/de/readme.txt
=> readme: fix some typos

data/RTTR/texte/de/readme.txt
part of #1044 , I'll check the english one when this got merged.
=> End of line fixes for the german readme

data/RTTR/texte/readme.txt
=> English readme fixups

.travis.yml, tests/s25Main/network/TestServer.cpp, tests/s25Main/network/TestServer.h, tests/s25Main/network/main.cpp, tests/s25Main/network/testLobby.cpp, tools/ci/travisBuild.sh
=> Support Boost 1.70

extras/videoDrivers/SDL2/VideoSDL2.cpp, extras/videoDrivers/SDL2/VideoSDL2.h, extras/videoDrivers/WinAPI/WinAPI.cpp, libs/driver/src/VideoDriver.cpp, libs/s25main/drivers/VideoDriverWrapper.cpp, tests/mockupDrivers/MockupVideoDriver.cpp, tests/mockupDrivers/MockupVideoDriver.h, tests/s25Main/UI/testVideoDriver.cpp
Follow-up for issues mentioned in #1066
This fixes WinAPI+OpenGL, wrongly selected resolutions and improves usability with SDL (window centred and possibly resized to fit screen)
=> Fix videodrivers

libs/s25main/Loader.cpp
=> Fix assertion failure in loader::GetArchive

libs/s25main/lua/LuaWorld.cpp
=> Add polarbear to lua

.travis.yml, tools/ci/travisBuild.sh
Aims to fix the apple builds on travis
=> Fix apple builds

libs/s25main/TerrainRenderer.cpp
this makes the compile work, tested with clang-10.0.0_rc2
=> fix compile with clang-10 in TerrainRenderer

libs/s25main/Settings.cpp, libs/s25main/Settings.h, libs/s25main/desktops/dskLAN.cpp, libs/s25main/desktops/dskLobby.cpp, libs/s25main/ingameWindows/iwLobbyConnect.cpp, libs/s25main/ingameWindows/iwLobbyConnect.h
Also removes the superflous EMail field for improved usability
Fixes #1194
=> Fix crash on clicking connect with no game selected

libs/s25main/ingameWindows/iwOptionsWindow.cpp
=> Fix crash on enable/disable ingame music or sound

libs/s25client/s25client.cpp, libs/s25main/Loader.cpp, libs/s25main/Loader.h, libs/s25main/MusicPlayer.cpp, libs/s25main/MusicPlayer.h, libs/s25main/Playlist.cpp, libs/s25main/Playlist.h, libs/s25main/QuickStartGame.cpp, libs/s25main/RttrForeachPt.h, libs/s25main/desktops/dskBenchmark.cpp, libs/s25main/desktops/dskCredits.cpp, libs/s25main/desktops/dskGameLoader.cpp, libs/s25main/desktops/dskGameLoader.h, libs/s25main/desktops/dskSplash.cpp, libs/s25main/gameData/ApplicationLoader.cpp, libs/s25main/gameData/ApplicationLoader.h, libs/s25main/gameData/GameLoader.cpp, libs/s25main/gameData/GameLoader.h, libs/s25main/ingameWindows/iwMusicPlayer.cpp, tests/s25Main/UI/testSmartBitmap.cpp
Fixes #1218 
Larger refactoring to get loading of data into a reusable class. Also avoid the use of the Singletons (want to get rid of them eventually)
Not fully satisfied with the solution as there is still duplicated code. More maybe in future PRs
=> Fix crash on map param

libs/s25main/controls/ctrlDeepening.h, libs/s25main/controls/ctrlTextButton.cpp, libs/s25main/controls/ctrlTextButton.h, libs/s25main/controls/ctrlTextDeepening.cpp, libs/s25main/controls/ctrlTextDeepening.h, libs/s25main/ingameWindows/iwMainMenu.cpp, libs/s25main/ingameWindows/iwTools.cpp, tests/s25Main/UI/testControls.cpp
The text/button were to small, adjusted sizes.
Also limit number of tools to order to 99 not 100 (causing this again)
Fixes #1207
=> Fix text not being shown in tool-window and main menu

libs/s25main/desktops/dskMainMenu.cpp
I do not remove it, since we want the intro perhaps for 1.0
see #1234
=> disable intro button

libs/s25main/Loader.cpp, libs/s25main/TerrainRenderer.cpp, libs/s25main/customborderbuilder.cpp, libs/s25main/desktops/dskCredits.cpp, libs/s25main/mapGenerator/ObjectGenerator.cpp, libs/s25main/mapGenerator/ObjectGenerator.h, libs/s25main/mapGenerator/RandomMapGenerator.cpp, libs/s25main/ogl/glAllocator.cpp, libs/s25main/ogl/glAllocator.h, libs/s25main/ogl/glArchivItem_Bitmap.cpp, libs/s25main/ogl/glArchivItem_BitmapBase.cpp, libs/s25main/ogl/glArchivItem_Sound_Other.cpp, libs/s25main/ogl/glFont.cpp, tests/s25Main/UI/testSmartBitmap.cpp, tests/s25Main/mapGenerator/testObjectGenerator.cpp
=>  Fix credit image query and transparency 

libs/s25main/Playlist.cpp
I thought this was fixed already. Seems to be forgotten
=> Remove commented includes

libs/s25main/ingameWindows/iwAIDebug.cpp, libs/s25main/ingameWindows/iwAIDebug.h
=> Fix multiline debug string in AI debug window

libs/s25main/desktops/dskCredits.cpp, libs/s25main/desktops/dskCredits.h, libs/s25main/desktops/dskGameLoader.cpp, libs/s25main/desktops/dskGameLoader.h
Fixes #1244
This can occur when the mapping.links override has the wrong format
=> Handle error on loading game resources

libs/common/include/helpers/containerUtils.h, libs/s25main/ai/aijh/AIConstruction.cpp, libs/s25main/ai/aijh/AIPlayerJH.cpp, libs/s25main/ai/aijh/AIPlayerJH.h, libs/s25main/gameTypes/MapCoordinates.h, libs/s25main/ingameWindows/iwMapDebug.cpp, libs/s25main/ingameWindows/iwMapDebug.h, libs/s25main/notifications/NodeNote.h, libs/s25main/world/GameWorldBase.h, libs/s25main/world/GameWorldGame.cpp, tests/common/testContainerUtils.cpp, tests/s25Main/integration/testAI.cpp, tests/s25Main/integration/testBuilding.cpp, tests/s25Main/integration/testTerritoryRegion.cpp
Make the AI update its BQ map also on owner change
The players view on the BQ depends on the ownership of surrounding nodes hence use th ownership changed note and update BQ on that node and surrounding
Fixes #1127, fixes #1128 (same issue)
=> Fix BQ update in AI map

.travis.yml, libs/s25main/GameCommand.h, libs/s25main/GameCommands.h, libs/s25main/gameTypes/FoWNode.h, libs/s25main/random/XorShift.h
=> Add missing includes and update travis

README.md, appveyor.yml
=> Require MSVC 2017+

libs/s25main/Replay.cpp, libs/s25main/Savegame.cpp, libs/s25main/Savegame.h, libs/s25main/SerializedGameData.h, libs/s25main/Ware.cpp, libs/s25main/desktops/dskSinglePlayer.cpp, libs/s25main/ingameWindows/iwSave.cpp, libs/s25main/network/GameClient.cpp, libs/s25main/network/GameServer.cpp, libs/s25main/nodeObjs/noFlag.cpp, tests/s25Main/integration/testSerialization.cpp
Avoids serializing bogus values
Fixes #1293
=> Initialize Ware::next_dir

libs/s25main/GlobalGameSettings.cpp, libs/s25main/GlobalGameSettings.h, libs/s25main/Loader.cpp, libs/s25main/Ware.cpp, libs/s25main/buildings/nobBaseWarehouse.cpp, libs/s25main/buildings/nobHarborBuilding.cpp, libs/s25main/desktops/dskCredits.cpp, libs/s25main/gameData/JobConsts.cpp, libs/s25main/gameData/JobConsts.h, libs/s25main/gameData/ShieldConsts.h, libs/s25main/ingameWindows/iwBaseWarehouse.cpp, libs/s25main/ingameWindows/iwShip.cpp, libs/s25main/ingameWindows/iwWares.cpp, libs/s25main/ingameWindows/iwWares.h, libs/s25main/nodeObjs/noShip.cpp, libs/s25main/nodeObjs/noShip.h
Fix drawing of ship cargo figures which was introduced by #1261 where getting the bob ID was accidentally removed
Fixes #1298
Also avoids more issues by using EnumArray and fixing stuff touched to be cleaner and a typo `GetNumScoutsExedition`
=> Fix ship cargo drawing and refactor related stuff

libs/common/include/helpers/EnumArray.h, libs/s25main/GamePlayer.cpp, libs/s25main/gameData/SettingTypeConv.cpp, libs/s25main/gameData/SettingTypeConv.h, libs/s25main/gameTypes/GoodTypes.h, libs/s25main/gameTypes/SettingsTypes.h, libs/s25main/ingameWindows/iwBuilding.cpp, libs/s25main/ingameWindows/iwBuildingSite.cpp, libs/s25main/ingameWindows/iwMerchandiseStatistics.cpp, libs/s25main/ingameWindows/iwMilitaryBuilding.cpp, libs/s25main/ingameWindows/iwTrade.cpp, libs/s25main/ingameWindows/iwTransport.cpp, libs/s25main/ingameWindows/iwTransport.h, libs/s25main/ingameWindows/iwWares.cpp
Select the first button on creation, fixes #1300
Also some refactoring to unify the arrays
=> Fix crash in transport window when nothing is selected

.gitignore, libs/s25main/desktops/dskCredits.cpp, libs/s25main/desktops/dskCredits.h
fixes #1236
@Flamefire  perhaps you can change it to use the animation system? I'm honest I don't have the time to look into it to find out how that works
=> update credit skip to work again, update credits

libs/common/include/helpers/mathFuncs.h, libs/s25main/GameManager.cpp, libs/s25main/QuickStartGame.cpp, libs/s25main/Settings.cpp, libs/s25main/Settings.h, libs/s25main/SoundManager.cpp, libs/s25main/Window.cpp, libs/s25main/Window.h, libs/s25main/desktops/dskCredits.cpp, libs/s25main/desktops/dskGameLoader.cpp, libs/s25main/desktops/dskLAN.cpp, libs/s25main/desktops/dskLobby.cpp, libs/s25main/desktops/dskMainMenu.cpp, libs/s25main/desktops/dskOptions.cpp, libs/s25main/desktops/dskSplash.cpp, libs/s25main/ingameWindows/iwBuildOrder.cpp, libs/s25main/ingameWindows/iwDistribution.cpp, libs/s25main/ingameWindows/iwLobbyRanking.cpp, libs/s25main/ingameWindows/iwLobbyServerInfo.cpp, libs/s25main/ingameWindows/iwMapDebug.cpp, libs/s25main/ingameWindows/iwMilitary.cpp, libs/s25main/ingameWindows/iwOptionsWindow.cpp, libs/s25main/ingameWindows/iwTools.cpp, libs/s25main/ingameWindows/iwTransport.cpp, libs/s25main/network/GameClient.cpp, libs/s25main/ogl/MusicItem.cpp, libs/s25main/ogl/SoundEffectItem.cpp, tests/common/testMathHelpers.cpp, tests/s25Main/audio/testSounds.cpp
Also fix some CI failures (signedness and parameter name)
=> Introduce linear interpolation function

libs/s25main/ingameWindows/iwEconomicProgress.cpp, libs/s25main/ingameWindows/iwMerchandiseStatistics.cpp, libs/s25main/ingameWindows/iwStatistics.cpp
Fixes the following visual bug for some minimized windows.
=> Fix visual bug for some minimized windows

libs/s25main/SerializedGameData.cpp, libs/s25main/figures/nofGeologist.cpp
We didn't serialize fish and water before where not serializing water was an actual bug (it is used with exhaustible water addon)
Serializing fish is not required now but makes the code easier.
Fixes #1332
=> Fix geologist loading

cpp.hint, libs/s25main/BasePlayerInfo.cpp, libs/s25main/EventManager.cpp, libs/s25main/FOWObjects.h, libs/s25main/GlobalGameSettings.cpp, libs/s25main/SerializedGameData.cpp, libs/s25main/figures/nofCharburner.cpp, libs/s25main/figures/nofCharburner.h, libs/s25main/figures/nofTradeDonkey.cpp, libs/s25main/figures/nofTradeLeader.cpp, libs/s25main/gameTypes/AIInfo.cpp, libs/s25main/gameTypes/AIInfo.h, libs/s25main/gameTypes/ChatDestination.h, libs/s25main/gameTypes/GameSettingTypes.h, libs/s25main/gameTypes/MapType.h, libs/s25main/gameTypes/Resource.h, libs/s25main/gameTypes/TeamTypes.h, libs/s25main/network/GameMessages.h, tests/s25Main/integration/testSerialization.cpp, tests/s25Main/integration/testTrading.cpp, tests/s25Main/simple/testGameTypes.cpp, tests/testHelpers/rttr/test/random.hpp
First was a `>=` vs `>` and the 2nd a missing return
Add tests for both cases and used more of push/popEnum for verification of gamedata.
Also added test case for #1337 but couldn't find anything
=> Fix loading of Fish and crash on failed trade

libs/s25main/mapGenerator/HeadQuarters.cpp, libs/s25main/mapGenerator/HeadQuarters.h, libs/s25main/mapGenerator/Map.cpp, libs/s25main/mapGenerator/Map.h, libs/s25main/mapGenerator/Resources.cpp, tests/s25Main/mapGenerator/testHeadQuarters.cpp, tests/s25Main/mapGenerator/testMap.cpp, tests/s25Main/mapGenerator/testRandomMap.cpp, tests/s25Main/mapGenerator/testResources.cpp
Just removed some useless code to slightly improve readability.
=> Refactored code for storing HQ positions

libs/s25main/desktops/dskSelectMap.cpp, libs/s25main/mapGenerator/HeadQuarters.cpp, libs/s25main/mapGenerator/HeadQuarters.h, libs/s25main/mapGenerator/RandomMap.cpp, libs/s25main/mapGenerator/Resources.cpp, tests/s25Main/mapGenerator/testHeadQuarters.cpp, tests/s25Main/mapGenerator/testRandomMap.cpp
Probably better to create a custom exception type here, instead of a `std::runtime_error`?
=> #1346 improve error handling on failed HQ placement

libs/s25main/ingameWindows/iwMapGenerator.cpp, libs/s25main/mapGenerator/MapSettings.h, libs/s25main/mapGenerator/RandomMap.cpp, libs/s25main/mapGenerator/RandomMap.h, libs/s25main/mapGenerator/RandomUtility.cpp, libs/s25main/mapGenerator/RandomUtility.h, libs/s25main/mapGenerator/TextureHelper.cpp, libs/s25main/mapGenerator/TextureHelper.h, libs/s25main/mapGenerator/Textures.cpp, libs/s25main/mapGenerator/Textures.h, libs/s25main/mapGenerator/Triangles.cpp, libs/s25main/mapGenerator/Triangles.h, tests/s25Main/mapGenerator/testRandomUtility.cpp
I think this looks a bit more interesting. I planned to add the option to configure rivers in the UI later. Could do it now or in the same PR. What would you prefer?
=> Mountain river transitions

libs/s25main/ingameWindows/iwMapGenerator.cpp, libs/s25main/mapGenerator/MapSettings.h, libs/s25main/mapGenerator/RandomMap.cpp, libs/s25main/mapGenerator/Resources.cpp, libs/s25main/mapGenerator/Resources.h, tests/s25Main/mapGenerator/testResources.cpp
Should be a fairly simple change, just making some "magic constants" configurable in the UI. Couldn't really see any drawback for this.
=> Configurable stone piles and trees for random maps

libs/s25main/mapGenerator/Algorithms.h, libs/s25main/mapGenerator/Harbors.cpp, libs/s25main/mapGenerator/Harbors.h, libs/s25main/mapGenerator/RandomMap.cpp, libs/s25main/world/MapBase.cpp, libs/s25main/world/MapBase.h, tests/s25Main/mapGenerator/testAlgorithms.cpp
* little bit of refactoring of harbor positioning
* choose random center for water & mixed maps
Let me know what you think, maybe there's more to improve around harbor positioning.
=> Random map harbor placement

libs/s25main/mapGenerator/RandomMap.cpp, libs/s25main/mapGenerator/RandomMap.h
My last changes made the river generation slightly weird for water & mixed maps. The central point for map generation became a random point but the rivers are still generated at the middle of the map.
=> Fixed river generation

libs/s25main/desktops/dskGameInterface.cpp
=> Disable player swapping in multiplayer games

libs/s25main/GamePlayer.cpp, libs/s25main/figures/nofBuildingWorker.h, libs/s25main/figures/nofHunter.cpp, libs/s25main/world/World.cpp, tests/s25Main/integration/testSerialization.cpp
The shooting_dir was not initialized, so bogus values were serialized in some states
=> Fix savegame corruption due to potentially uninitialized value in nofHunter

libs/s25main/SerializedGameData.cpp, libs/s25main/figures/nofHunter.cpp, tests/s25Main/integration/testSerialization.cpp
Fix CI after https://github.com/Return-To-The-Roots/s25client/pull/1389
=> Followup to: Fix hunter savegame corruption

libs/s25main/ai/AIInterface.cpp, libs/s25main/ai/AIInterface.h, libs/s25main/ai/AIPlayer.h, libs/s25main/ai/aijh/AIPlayerJH.cpp, libs/s25main/ai/aijh/AIPlayerJH.h, libs/s25main/gameTypes/GameTypesOutput.h, libs/s25main/network/GameClient.cpp, libs/s25main/network/GameClientGF_Game.cpp, libs/s25main/network/GameMessage_Chat.cpp, libs/s25main/network/GameMessage_Chat.h, libs/s25main/network/GameMessages.h, tests/s25Main/integration/testAI.cpp, tests/s25Main/integration/testSerialization.cpp
Closes #1381 
@jdoerfert Does this interface suffice?
@Flow86 Testing the code in the GameClient is still too hard to do in a unit test. I tested the changes in AIPlayerJH manually which writes a message shortly after start and that works.
As a note: The chat message isn't send immediately but with the next NWF. I think that is fair given that they happen often enough and it keeps the "fetch" code close by
=> Add functions so AI can send and receive chat messages

libs/s25main/Game.cpp, libs/s25main/GameManager.cpp, libs/s25main/Loader.cpp, libs/s25main/TerrainRenderer.cpp, libs/s25main/buildings/nobBaseMilitary.cpp, libs/s25main/buildings/nobBaseWarehouse.cpp, libs/s25main/desktops/dskSelectMap.cpp, libs/s25main/desktops/dskSplash.cpp, libs/s25main/desktops/dskSplash.h, libs/s25main/ogl/glSmartBitmap.cpp, libs/s25main/ogl/glSmartBitmap.h, libs/s25main/resources/ArchiveLoader.cpp, libs/s25main/world/MapSerializer.cpp
See https://www.siedler25.org/index.php?com=forum&mod=forum&action=thread&id=1677&start=-1#last
=> Fix a double-free when a defender is chosen out of the leave list

extras/videoDrivers/SDL2/VideoSDL2.cpp, libs/s25main/drivers/VideoDriverWrapper.cpp
=> Remove version from window title

libs/s25main/DataChangedObservable.cpp, libs/s25main/EconomyModeHandler.cpp, libs/s25main/EventManager.cpp, libs/s25main/GameCommands.cpp, libs/s25main/GameCommands.h, libs/s25main/GamePlayer.cpp, libs/s25main/ai/aijh/AIConstruction.cpp, libs/s25main/ai/aijh/AIPlayerJH.cpp, libs/s25main/buildings/noBuildingSite.cpp, libs/s25main/buildings/nobBaseMilitary.cpp, libs/s25main/buildings/nobBaseWarehouse.cpp, libs/s25main/buildings/nobHarborBuilding.cpp, libs/s25main/buildings/nobMilitary.cpp, libs/s25main/buildings/nobMilitary.h, libs/s25main/figures/nofAttacker.cpp, libs/s25main/figures/nofCatapultMan.cpp, libs/s25main/ingameWindows/iwTrade.cpp
=> Fix infinite recursion in some attack situations 

libs/s25main/Loader.cpp, libs/s25main/MusicPlayer.cpp, libs/s25main/Playlist.cpp, libs/s25main/network/GameClient.cpp, libs/s25main/network/GameServer.cpp, libs/s25main/resources/ArchiveLoader.cpp
=> Remove duplicate quotes in log messages

libs/common/include/helpers/EnumArray.h, libs/s25main/GameCommands.cpp, libs/s25main/GameCommands.h, libs/s25main/GamePlayer.cpp, libs/s25main/GamePlayer.h, libs/s25main/ai/aijh/AIPlayerJH.cpp, libs/s25main/figures/nofMetalworker.cpp, libs/s25main/gameData/ToolConsts.h, libs/s25main/gameTypes/GoodTypes.h, libs/s25main/gameTypes/SettingsTypes.h, libs/s25main/ingameWindows/iwBuildOrder.h, libs/s25main/ingameWindows/iwDistribution.h, libs/s25main/ingameWindows/iwMilitary.h, libs/s25main/ingameWindows/iwTools.cpp, libs/s25main/ingameWindows/iwTools.h, libs/s25main/ingameWindows/iwTransport.h, libs/s25main/random/Random.h, tests/common/testEnumArray.cpp, tests/s25Main/integration/testGameCommands.cpp, tests/s25Main/integration/testProduction.cpp, tests/s25Main/simple/testGameTypes.cpp
Followup to #1415 to avoid magic numbers which has lead to the bug(s) fixed in that PR by using a strong-enum.
=> Introduce Tool enum

CMakeLists.txt
`if(${VARIABLE} ...` is wrong due to variable substitution.
Fixed that and using the project command to set the version which will then also be the default for CPack
=> Fix and improve version checks

.github/workflows/unit-tests.yml
=> Update GCC 6 OS to 18.04

libs/s25main/ingameWindows/iwAction.cpp
Add missing parent call to Close
Fixes #1459
=> Fix closing of iwAction

libs/s25main/GamePlayer.cpp, libs/s25main/GamePlayer.h, libs/s25main/SerializedGameData.cpp, libs/s25main/network/GameClient.cpp, libs/s25main/network/GameMessages.cpp, libs/s25main/network/GameMessages.h, libs/s25main/network/GameServer.cpp, libs/s25main/nodeObjs/noFlag.cpp
See https://github.com/Return-To-The-Roots/s25client/issues/1449 and help a bit for https://github.com/Return-To-The-Roots/s25client/issues/1435
Fixes #1449
=> Fix crash when flag is captured while having active flag workers and enhance connect fail message for version mismatch

libs/common/include/helpers/EnumArray.h, libs/s25main/SerializedGameData.cpp, libs/s25main/desktops/dskGameInterface.cpp, libs/s25main/gameTypes/BuildingQuality.h, libs/s25main/gameTypes/MapNode.cpp, libs/s25main/world/BQCalculator.h, libs/s25main/world/GameWorldView.cpp, libs/s25main/world/MapLoader.cpp, tests/s25Main/benchmarks/RealWorld_MapTests.cpp, tests/s25Main/integration/testSerialization.cpp, tests/s25Main/integration/testWorld.cpp, tests/s25Main/simple/testGameTypes.cpp
A harbor spot is like a castle spot with additional harbor building
Fixes #1473
Also adds tests for that
=> Allow all building types on Harbor spots 

tests/s25Main/integration/testWorld.cpp
Rebase of #938
Requires  rebase(!)-merge of https://github.com/Return-To-The-Roots/s25maps/pull/1
@Spikeone I think I got everything from your PR, which you can close since you deleted your fork...
=> Cleaned up new maps folder

libs/s25main/network/GameClient.cpp, tests/s25Main/network/testGameClient.cpp
The message handler wrongly only counted the map size as received not also the (just received) lua size and hence did never finish.
Also add buffer overflow protection to the map-receive code and test both issues.
Loading the first campaign map now works for me and the test did reproduce the issue and now doesn't fail anymore.
Fixes #1494
=> Fix transmission handling of maps with LUA scripts

CMakeLists.txt
This option enables the possibility for a package maintainer to let RTTR_GAMEDIR to a place
which is not in control of the packaging system. Thats needed when RTTR_GAMEDIR should point
to $HOME, if the packaging system prevents writes to the RTTR_GAMEDIR on package build time.
The default keeps the old behavior.
To explain a bit more about the motivation. On discord there was a short discussion in the development channel between Flow and myself. I was asking how i can archive a build of RTTR which does not "depend" on having the game files on a predictable place in FHS. The reason for that is that i am trying to create a package for rttr for the packaging system "nix". 
This contains a read-only store located at `/nix/store`. As S2 games are in common cases stored either in the rttr …
=> Add CMake option to not install placeholder files

doc/lua/constants.md, doc/lua/functions.md, libs/s25main/lua/LuaInterfaceGame.cpp, libs/s25main/lua/LuaPlayer.cpp, libs/s25main/lua/LuaPlayer.h, tests/s25Main/lua/testLua.cpp, tests/s25Main/lua/testLuaConstants.cpp
=> Add lua function GetStatisticsValue()

libs/s25main/network/GameClient.cpp
This has turned into an error in Boost 1.81
Fixes #1551
=> Fix compatibility with Boost 1.74+/1.81+

libs/s25main/buildings/nobBaseWarehouse.cpp
=> Fix Test_autoplay after breaking it with Fix of #1559

.github/workflows/release.yml, .github/workflows/static-analysis.yml, .github/workflows/unit-tests.yml, libs/s25main/Debug.cpp
=> sort matrix according to issue description

libs/s25main/Loader.cpp, libs/s25main/nodeObjs/noStaticObject.cpp, libs/s25main/nodeObjs/noStaticObject.h, tests/s25Main/lua/testLua.cpp
=> #1509 Do not cache texture for animated objects (like open gate)

data/RTTR/gamedata/world/wasteland.lua
Fixes Return-To-The-Roots:master#1514
fixes #1514
=> #1514 Use correct palAnimIdx for wasteland to animate lava

extras/videoDrivers/SDL2/VideoSDL2.cpp
Add paste functionality on non-Windows platforms using `SDL_GetClipboardText()` et al. instead of WinAPI functions.
=> Implement platform-agnostic paste in SDL2 backend

tests/s25Main/network/TestServer.cpp, tests/s25Main/network/main.cpp
Add more checks and retries to avoid that often failing test on GHA with macos
=> Fix flakyness in Test_network on CI

tools/release/debian/s25rttr.metainfo.xml
See https://freedesktop.org/software/appstream/docs/chap-Metadata.html and https://hughsie.github.io/oars/
=> Added AppStream metadata

data/RTTR/campaigns/world/campaign.lua, doc/AddingCustomCampaign.md, libs/libGamedata/gameData/CampaignDescription.cpp, libs/libGamedata/gameData/CampaignDescription.h, libs/libGamedata/gameData/SelectionMapInputData.cpp, libs/libGamedata/gameData/SelectionMapInputData.h, libs/libGamedata/lua/CampaignDataLoader.cpp, libs/libGamedata/lua/CheckedLuaTable.h, libs/s25main/desktops/dskCampaignMissionMapSelection.cpp, libs/s25main/desktops/dskCampaignMissionMapSelection.h, libs/s25main/desktops/dskCampaignSelection.cpp, libs/s25main/desktops/dskCampaignSelection.h, tests/s25Main/UI/testMapSelection.cpp, tests/s25Main/campaign/testCampaignLuaFile.cpp
Add selection map screen to campaign lua and use it for world campaign.
Add documention.
=> Add map selection to campaign lua

libs/libGamedata/lua/GameDataLoader.cpp, libs/libGamedata/lua/GameDataLoader.h, tests/s25Main/network/testGameClient.cpp, tests/testHelpers/CMakeLists.txt, tests/testHelpers/rttr/test/ConfigOverride.hpp
Fix off-by-one in counting of includes
Remove a try-catch that cannot be reached.
Include refactoring commit from #1759 to reduce the size of that PR
=> Minor refactor of GameDataLoader

tools/release/bin/rttr.sh.cmake
Fixes https://github.com/Return-To-The-Roots/s25client/issues/1763
=> Fix quoting in rttr.sh

libs/s25main/ingameWindows/iwSettings.cpp
=> Rename smart-cursor option in ingame dialog
